import type {ServiceTime} from '@/features/public/server';
import {obj,str,num,bool,array,nullable,parsePage} from "./workspace";
export type ContentKind="PAGE"|"HOMEPAGE"|"MINISTRY"|"LEADERSHIP"|"SERMON"|"GALLERY"|"TESTIMONY";
export interface EditorialData {image_id:string|null;public_name:string;public_title:string;meeting_information:string;public_contact:string;speaker:string;sermon_date:string|null;scripture_reference:string;series:string;youtube_url:string;audio_url:string;images:{asset_id:string;caption:string;alt_text:string}[];display_order:number;hero_headline:string;hero_text:string;primary_label:string;primary_href:string;secondary_label:string;secondary_href:string;section_order:string[];events_count:number;ministries_count:number;announcements_count:number;gallery_count:number;featured_slugs:string[];consent_reference:string}
export interface Draft {kind:ContentKind;slug:string;title:string;summary:string;body:string;seo_title:string;seo_description:string;data:EditorialData}
export interface ContentRecord {id:string;kind:ContentKind;slug:string;title:string;status:string;draft:Draft;ministry_id:string|null;member_id:string|null;updated_at:string;published_at:string|null;has_unpublished_changes:boolean}
export interface SiteConfiguration {church_name:string;full_name:string;tagline:string;address:string;public_phone:string;public_email:string;timezone:string;service_times:ServiceTime[];social_links:{label:string;url:string}[];map_url:string;footer_text:string;contact_form_enabled:boolean;visitor_form_enabled:boolean;prayer_form_enabled:boolean}
export interface SettingsRecord {data:SiteConfiguration;updated_at:string|null;published_at:string|null}
export interface MediaRecord {id:string;alt_text:string;caption:string;status:string;width:number;height:number;contains_children:boolean;consent_attested:boolean;consent_reference:string;updated_at:string;preview_url:string}
export interface Communication {id:string;slug:string;title:string;scope:string;ministry_id:string|null;status:string;updated_at:string;published_at:string|null;description?:string;body?:string;event_type?:string;visibility?:string;audience?:string;start_datetime?:string;end_datetime?:string|null;location?:string;image_id?:string|null;publish_from?:string|null;publish_until?:string|null;priority?:number}
export interface Inquiry {id:string;kind:string;first_name:string;last_name:string;phone:string;email:string;message:string;private_notes:string;status:string;contact_permission:boolean;preferred_contact:string;visit_date:string|null;assigned_to:string|null;converted_member_id:string|null;updated_at:string;created_at:string}
export function parseContent(value:unknown):ContentRecord {const o=obj(value),draft=obj(o.draft),d=obj(draft.data);
const data:EditorialData={image_id:nullable(d.image_id,str),public_name:str(d.public_name),public_title:str(d.public_title),meeting_information:str(d.meeting_information),public_contact:str(d.public_contact),speaker:str(d.speaker),sermon_date:nullable(d.sermon_date,str),scripture_reference:str(d.scripture_reference),series:str(d.series),youtube_url:str(d.youtube_url),audio_url:str(d.audio_url),images:array(d.images,value=>{const i=obj(value);return{asset_id:str(i.asset_id),caption:str(i.caption),alt_text:str(i.alt_text)}}),display_order:num(d.display_order),hero_headline:str(d.hero_headline),hero_text:str(d.hero_text),primary_label:str(d.primary_label),primary_href:str(d.primary_href),secondary_label:str(d.secondary_label),secondary_href:str(d.secondary_href),section_order:array(d.section_order,str),events_count:num(d.events_count??6),ministries_count:num(d.ministries_count??3),announcements_count:num(d.announcements_count??3),gallery_count:num(d.gallery_count??5),featured_slugs:array(d.featured_slugs,str),consent_reference:str(d.consent_reference)};
return{id:str(o.id),kind:str(o.kind) as ContentKind,slug:str(o.slug),title:str(o.title),status:str(o.status),draft:{kind:str(draft.kind) as ContentKind,slug:str(draft.slug),title:str(draft.title),summary:str(draft.summary),body:str(draft.body),seo_title:str(draft.seo_title),seo_description:str(draft.seo_description),data},ministry_id:nullable(o.ministry_id,str),member_id:nullable(o.member_id,str),updated_at:str(o.updated_at),published_at:nullable(o.published_at,str),has_unpublished_changes:bool(o.has_unpublished_changes)};}
export function parseSettings(value:unknown):SettingsRecord {const o=obj(value),d=obj(o.data);return{updated_at:nullable(o.updated_at,str),published_at:nullable(o.published_at,str),data:{church_name:str(d.church_name),full_name:str(d.full_name),tagline:str(d.tagline),address:str(d.address),public_phone:str(d.public_phone),public_email:str(d.public_email),timezone:str(d.timezone??'UTC'),service_times:array(d.service_times,value=>{const s=obj(value);return{id:nullable(s.id??null,str),name:str(s.name),schedule:str(s.schedule),day_of_week:nullable(s.day_of_week??null,str),start_time:nullable(s.start_time??null,str),end_time:nullable(s.end_time??null,str),description:str(s.description??''),location:str(s.location??''),display_order:num(s.display_order??0),active:bool(s.active??true),featured:bool(s.featured??true),created_at:nullable(s.created_at??null,str),updated_at:nullable(s.updated_at??null,str)}}),social_links:array(d.social_links,value=>{const s=obj(value);return{label:str(s.label),url:str(s.url)}}),map_url:str(d.map_url),footer_text:str(d.footer_text),contact_form_enabled:bool(d.contact_form_enabled),visitor_form_enabled:bool(d.visitor_form_enabled),prayer_form_enabled:bool(d.prayer_form_enabled)}};}
export function parseMedia(value:unknown):MediaRecord {const o=obj(value);return{id:str(o.id),alt_text:str(o.alt_text),caption:str(o.caption),status:str(o.status),width:num(o.width),height:num(o.height),contains_children:bool(o.contains_children),consent_attested:bool(o.consent_attested),consent_reference:str(o.consent_reference),updated_at:str(o.updated_at),preview_url:str(o.preview_url)};}
export function parseCommunication(value:unknown):Communication {const o=obj(value);const r:Communication={id:str(o.id),slug:str(o.slug),title:str(o.title),scope:str(o.scope),ministry_id:nullable(o.ministry_id,str),status:str(o.status),updated_at:str(o.updated_at),published_at:nullable(o.published_at,str)};
for(const k of ["description","body","event_type","visibility","audience","start_datetime","location"] as const)if(k in o)r[k]=str(o[k]);
for(const k of ["end_datetime","image_id","publish_from","publish_until"] as const)if(k in o)r[k]=nullable(o[k],str);if("priority"in o)r.priority=num(o.priority);return r;}
export function parseInquiry(value:unknown):Inquiry {const o=obj(value);return{id:str(o.id),kind:str(o.kind),first_name:str(o.first_name),last_name:str(o.last_name),phone:str(o.phone),email:str(o.email),message:str(o.message),private_notes:str(o.private_notes),status:str(o.status),contact_permission:bool(o.contact_permission),preferred_contact:str(o.preferred_contact),visit_date:nullable(o.visit_date,str),assigned_to:nullable(o.assigned_to,str),converted_member_id:nullable(o.converted_member_id,str),updated_at:str(o.updated_at),created_at:str(o.created_at)};}
export const parseContents=parsePage(parseContent),parseMediaList=parsePage(parseMedia),parseCommunications=parsePage(parseCommunication),parseInquiries=parsePage(parseInquiry);
export function parseCandidates(value:unknown){return array(value,v=>{const o=obj(v);return{id:str(o.id),name:str(o.name),member_no:nullable(o.member_no,str)}});}
export function parseOverview(value:unknown){const o=obj(value);return{counts:array(o.counts,v=>{const r=obj(v);return{kind:str(r.kind),status:str(r.status),total:num(r.total)}})};}
