import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Clock3,CalendarDays,Heart,MapPin,Mail,Phone,Play,Headphones} from 'lucide-react';
import {getSite,publicImageUrl,fallbackConfiguration,canonicalOrigin,jsonLd,type PublicContent,type PublicImage,type PublicSite,type Configuration} from './server';
import {PublicPhoto} from './public-photo';
import {EventsCarousel} from './events-carousel';
import {LeadershipCard} from './leadership-card';
import {homeSectionOrder,localClock} from './home-format';
function photo(image:PublicImage|null|undefined){return image?{...image,url:publicImageUrl(image)}:null;}
function excerpt(value:string,limit=240){return value.length>limit?value.slice(0,limit).replace(/\s+\S*$/,'')+'…':value;}
function Heading({eyebrow,title,text,href,label}:{eyebrow:string;title:string;text?:string;href?:string;label?:string}){return<div className='homepage-heading'><div><p className='public-eyebrow'>{eyebrow}</p><h2>{title}</h2>{text&&<p>{text}</p>}</div>{href&&<Link className='public-text-link' href={href}>{label}<ArrowRight size={19} aria-hidden='true'/></Link>}</div>;}
function ServiceSection({config}:{config:Configuration}){const services=config.service_times.filter(item=>item.active!==false&&item.featured!==false);
  return<section className='homepage-section homepage-services' id='weekly-services'><Heading eyebrow='Make time to gather' title='Weekly Services' text={'Join us through the week. Times shown in '+config.timezone.replaceAll('_',' ')+'.'}/>
    {services.length?<div className='homepage-services-grid'>{services.map((service,index)=><article className='homepage-service' key={service.id||service.name+index}>
      <div className='homepage-service-top'><span>{service.day_of_week||'Gather with us'}</span><CalendarDays size={22} aria-hidden='true'/></div><h3>{service.name}</h3>
      {service.start_time&&service.end_time?<p className='homepage-service-time'><time dateTime={service.start_time}>{localClock(service.start_time)}</time><span>—</span><time dateTime={service.end_time}>{localClock(service.end_time)}</time></p>:<p className='homepage-service-legacy'>{service.schedule}</p>}
      {service.description&&<p className='homepage-service-description'>{service.description}</p>}{service.location&&<p className='homepage-service-location'><MapPin size={16} aria-hidden='true'/>{service.location}</p>}
      <Link className='public-text-link' href='/new-here'>Plan Your Visit<ArrowUpRight size={17} aria-hidden='true'/></Link></article>)}</div>:<div className='homepage-empty'><p>Contact the church for the current service schedule.</p><Link className='public-text-link' href='/contact'>Contact HOPFAN<ArrowRight size={18}/></Link></div>}
  </section>;
}
function Welcome({item,school=false}:{item:PublicContent;school?:boolean}){const paragraphs=(item.summary||item.body).split(/\n\s*\n/).filter(Boolean).slice(0,3);
  return<section className={'homepage-section homepage-split '+(school?'homepage-school':'homepage-welcome')}><PublicPhoto image={photo(item.image)} className='homepage-feature-photo'/><div><p className='public-eyebrow'>{school?'Faith for every generation':'Welcome to HOPFAN'}</p><h2>{item.title}</h2>{paragraphs.map((paragraph,index)=><p className='homepage-introduction' key={index}>{excerpt(paragraph,440)}</p>)}<Link className='public-button' href={school?'/sunday-school':'/about'}>{school?'Learn About Sunday School':'Discover Our Story'}<ArrowRight size={18} aria-hidden='true'/></Link></div></section>;
}
function MinistrySection({items}:{items:PublicContent[]}){return<section className='homepage-section homepage-ministries'><Heading eyebrow='Find your community' title='A place to connect and serve.' href='/ministries' label='Explore All Ministries'/><div className='homepage-ministry-grid' data-count={items.length}>{items.map(item=><Link className='homepage-ministry' href={'/ministries/'+item.slug} key={item.slug}><PublicPhoto image={photo(item.image)}/><div><h3>{item.public_name||item.title}</h3>{item.summary&&<p>{excerpt(item.summary,210)}</p>}<span className='public-text-link'>Learn More<ArrowRight size={18} aria-hidden='true'/></span></div></Link>)}</div></section>;}
function SermonSection({item}:{item:PublicContent}){return<section className='homepage-section homepage-sermon'><div className='homepage-split'><Link href={'/sermons/'+item.slug} className='homepage-sermon-visual' aria-label={'Watch message: '+item.title}><PublicPhoto image={photo(item.image)} className='homepage-feature-photo'/><span className='homepage-play'><Play size={28} aria-hidden='true'/></span></Link><div><p className='public-eyebrow'>Latest Message</p><h2>{item.title}</h2><p className='homepage-sermon-meta'>{item.speaker}{item.sermon_date&&<> · <time dateTime={item.sermon_date}>{new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(item.sermon_date+'T12:00:00Z'))}</time></>}</p>{item.scripture_reference&&<p className='homepage-scripture'>{item.scripture_reference}</p>}{item.summary&&<p className='homepage-introduction'>{excerpt(item.summary,400)}</p>}<div className='homepage-actions'><Link className='public-button' href={'/sermons/'+item.slug}>Watch Message<Play size={17} aria-hidden='true'/></Link>{(item.audio_url||(item as {media?:{media_type:string}[]}).media?.some(asset=>asset.media_type==='AUDIO'))&&<Link className='public-text-link' href={'/sermons/'+item.slug+'?mode=audio'}>Listen<Headphones size={18} aria-hidden='true'/></Link>}<Link className='public-text-link' href='/sermons'>All Sermons<ArrowRight size={18} aria-hidden='true'/></Link></div></div></div></section>;}
function GallerySection({site}:{site:PublicSite}){const galleryCount=site.gallery_count??5;const images:{image:PublicImage;slug:string;title:string}[]=[];const seen=new Set<string>();
  for(const album of site.galleries)for(const image of album.images?.length?album.images:album.image?[album.image]:[]){if(images.length>=galleryCount)break;if(!seen.has(image.url)){seen.add(image.url);images.push({image,slug:album.slug,title:album.title});}}
  if(!images.length)return null;
  return<section className='homepage-section homepage-gallery'><Heading eyebrow='Life in our community' title='Moments we share.' href='/gallery' label='View Gallery'/><div className='homepage-gallery-mosaic' data-count={images.length}>{images.map(({image,slug,title},index)=><Link href={'/gallery/'+slug} key={image.url} aria-label={'View '+title+': '+image.alt_text}><PublicPhoto image={photo(image)} sizes={index===0?'(max-width:650px) 50vw, 640px':'(max-width:650px) 50vw, 320px'}/></Link>)}</div></section>;
}
function ContactSection({config}:{config:Configuration}){return<section className='homepage-section homepage-contact'><div><p className='public-eyebrow'>We look forward to meeting you</p><h2>Find your way to HOPFAN.</h2><h3>{config.full_name||config.church_name}</h3><div className='homepage-contact-details'>{config.address&&<p><MapPin size={22} aria-hidden='true'/>{config.address}</p>}{config.public_phone&&<a href={'tel:'+config.public_phone}><Phone size={21} aria-hidden='true'/>{config.public_phone}</a>}{config.public_email&&<a href={'mailto:'+config.public_email}><Mail size={21} aria-hidden='true'/>{config.public_email}</a>}</div><div className='homepage-actions'>{config.map_url&&<a className='public-button' href={config.map_url} rel='noopener noreferrer'>Get Directions<ArrowUpRight size={18} aria-hidden='true'/></a>}<Link className='public-text-link' href='/contact'>Contact the Church<ArrowRight size={18} aria-hidden='true'/></Link></div></div>{config.service_times.length>0&&<aside className='homepage-contact-services'><Clock3 size={27} aria-hidden='true'/><h3>Gather with us</h3>{config.service_times.slice(0,4).map((service,index)=><div key={service.id||service.name+index}><strong>{service.name}</strong><p>{service.schedule}</p></div>)}<Link className='public-text-link' href='/new-here'>Plan Your Visit<ArrowRight size={18} aria-hidden='true'/></Link></aside>}</section>;}
export async function PublicHome(){const site=await getSite(),config={...fallbackConfiguration,...(site?.configuration??{})};
  const hero=site?.hero??{headline:'Welcome to HOPFAN.',text:'',primary_label:'Plan Your Visit',primary_href:'/new-here',secondary_label:'Explore Ministries',secondary_href:'/ministries',image:null};
  const order=[...new Set(site?.section_order??homeSectionOrder)];
  if(!order.includes('leadership'))order.splice(Math.max(0,order.indexOf('ministries')+1),0,'leadership');
  if(!order.includes('donate'))order.splice(order.includes('prayer')?order.indexOf('prayer'):order.length,0,'donate');
  const prayer=order.includes('prayer')&&config.prayer_form_enabled;
  return<div className='homepage'><script type='application/ld+json' dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':['Church','Organization'],name:config.full_name||config.church_name,url:canonicalOrigin()??undefined,telephone:config.public_phone||undefined,email:config.public_email||undefined,address:config.address?{'@type':'PostalAddress',streetAddress:config.address}:undefined})}}/>
    <section className='homepage-hero'><PublicPhoto image={photo(hero.image)} priority sizes='100vw' className='homepage-hero-photo'/><div className='homepage-hero-overlay'/><div className='homepage-hero-inner'><p className='public-eyebrow'>{config.full_name}</p><h1>{hero.headline}</h1>{hero.text&&<p className='homepage-hero-description'>{hero.text}</p>}<div className='homepage-actions'><Link className='public-button' href={hero.primary_href}>{hero.primary_label}<ArrowUpRight size={19} aria-hidden='true'/></Link><Link className='public-button public-button-outline' href={hero.secondary_href}>{hero.secondary_label}<ArrowRight size={18} aria-hidden='true'/></Link></div></div>{order.includes('services')&&<a className='homepage-hero-scroll' href='#weekly-services'><Clock3 size={18} aria-hidden='true'/>Our weekly services<ArrowRight size={17} aria-hidden='true'/></a>}</section>
    {!site&&<p className='public-service-notice' role='status'>Published church information is temporarily unavailable. Please try again shortly.</p>}
    {order.map(section=>{
      if(section==='services')return<ServiceSection key={section} config={config}/>;
      if(section==='events')return<section className='homepage-section homepage-events' key={section}><Heading eyebrow='Life together' title='Upcoming Events' text='Discover what is happening at HOPFAN.' href='/events' label='View All Events'/>{site?.events.length?<EventsCarousel key={site.events.map(item=>item.slug).join('|')} events={site.events.map(item=>({...item,image:item.image?{...item.image,url:publicImageUrl(item.image)}:null}))} timeZone={config.timezone}/>:<div className='homepage-empty'><CalendarDays size={32} aria-hidden='true'/><div><h3>{site?.events_available===false||!site?'Events are temporarily unavailable.':'New events will be announced soon.'}</h3><p>Keep in touch with the latest news from the church.</p></div><Link href='/announcements' className='public-text-link'>View Announcements<ArrowRight size={18} aria-hidden='true'/></Link></div>}<p className='homepage-timezone'>Event times are shown in {config.timezone.replaceAll('_',' ')}.</p></section>;
      if(section==='welcome'&&site?.welcome)return<Welcome key={section} item={site.welcome}/>;
      if(section==='ministries'&&site?.ministries.length)return<MinistrySection key={section} items={site.ministries}/>;
      if(section==='leadership'&&site?.leadership.length)return<section className='homepage-section homepage-leadership' key={section}><Heading eyebrow='Serving our community' title='Meet Our Leadership' href='/leadership' label='View All Leadership'/><div className='public-leadership-grid'>{site.leadership.slice(0,8).map(item=><LeadershipCard key={item.slug} slug={item.slug} name={item.public_name||item.title} role={item.public_title||''} summary={item.summary} image={item.image?{src:publicImageUrl(item.image),alt:item.image.alt_text}:null}/>)}</div></section>;
      if(section==='sermons'&&site?.sermons[0])return<SermonSection key={section} item={site.sermons[0]}/>;
      if(section==='sunday-school'&&site?.sunday_school)return<Welcome key={section} item={site.sunday_school} school/>;
      if(section==='announcements'&&site?.announcements.length)return<section className='homepage-section homepage-announcements' key={section}><Heading eyebrow='Stay connected' title='Church Announcements' href='/announcements' label='View All Announcements'/><div className='homepage-announcement-list'>{site.announcements.map((item,index)=><article key={item.slug}><span className='homepage-announcement-number' aria-hidden='true'>{String(index+1).padStart(2,'0')}</span><div><p className='public-eyebrow'>{item.priority>0?'Priority notice':'Church notice'}{item.published_at&&<> · <time dateTime={item.published_at}>{new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',timeZone:config.timezone}).format(new Date(item.published_at))}</time></>}</p><h3><Link href={'/announcements#'+item.slug}>{item.title}</Link></h3><p>{excerpt(item.body,230)}</p></div><Link className='homepage-announcement-link' href={'/announcements#'+item.slug} aria-label={'Read announcement: '+item.title}><ArrowUpRight size={24}/></Link></article>)}</div></section>;
      if(section==='gallery'&&site)return<GallerySection key={section} site={site}/>;
      if(section==='donate')return<section className='homepage-section homepage-giving' key={section}><div><p className='public-eyebrow'>Give with purpose</p><h2>Support the Mission</h2><p>Your giving helps HOPFAN continue its ministry, outreach, welfare and community work.</p></div><Link href='/donate' className='public-button'>Donate Now<ArrowRight size={19} aria-hidden='true'/></Link></section>;
      if(section==='prayer'&&prayer)return<section className='homepage-section homepage-prayer' key={section}><Heart size={38} aria-hidden='true'/><div><p className='public-eyebrow'>Need prayer?</p><h2>We would be honoured to pray with you.</h2><p>Your request goes privately to the church’s authorized prayer team.</p><div className='homepage-actions'><Link href='/prayer-request' className='public-button'>Submit a Prayer Request<ArrowRight size={18} aria-hidden='true'/></Link>{order.includes('visit')&&<Link href='/new-here' className='public-button public-button-outline'>Plan Your Visit<ArrowUpRight size={18} aria-hidden='true'/></Link>}</div></div></section>;
      if(section==='visit'&&!prayer)return<section className='homepage-section homepage-visit' key={section}><p className='public-eyebrow'>Planning your first visit?</p><h2>Let’s help you feel at home.</h2><Link href='/new-here' className='public-button'>Plan Your Visit<ArrowUpRight size={19} aria-hidden='true'/></Link></section>;
      if(section==='contact')return<ContactSection key={section} config={config}/>;
      return null;
    })}
  </div>;
}
