"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Play} from 'lucide-react';
import {useAuth} from '@/features/auth/auth-provider';
import {useResource} from '@/features/workspace/use-resource';
import {useFilters} from '@/features/workspace/directories';
import {RecordState,Pagination,Empty} from '@/features/workspace/records-ui';
import {AccessDenied,ErrorMessage} from '@/components/ui/feedback';
import {Button,Input,Card,Badge} from '@/components/ui/primitives';
import {OperationalModal} from '@/features/operations/operational-ui';
import {api} from '@/lib/api/client';
import {SermonUpload} from './upload';
import {parseSermon,parseSermons,parseOptions,parseOverview,parseTaxonomies,parseTaxonomy,emptyMetadata,type TaxonomyRecord} from './contracts';
import {fileSize,type SermonRecord,type SermonMetadata,type PrivateAsset} from './types';
function errorMessage(error:unknown){return error instanceof Error?error.message:'Unable to save the sermon.';}
const statuses=['ALL','DRAFT','PROCESSING','READY','SCHEDULED','PUBLISHED','ARCHIVED','FAILED'];
export function SermonCms(){const{user}=useAuth();const filters=useFilters();const[tab,setTab]=useState<'sermons'|'series'|'categories'>('sermons');const allowed=!!user?.permissions.includes('SERMON_VIEW');const overview=useResource(allowed?'/api/v1/sermons/overview':null,parseOverview);const options=useResource(allowed?'/api/v1/sermons/options':null,parseOptions);
  const list=useResource(allowed?'/api/v1/sermons?'+new URLSearchParams({page_number:String(filters.page),search:filters.params.get('search')||'',status:filters.params.get('status')||'ALL'}):null,parseSermons);
  if(!allowed)return<AccessDenied/>;
  return<><div className='page-heading'><div><p className='eyebrow'>HOPFAN SERMON MEDIA</p><h1>Sermons</h1><p>One message, with video, audio and study materials. Drafts stay private until published.</p></div>{user?.permissions.includes('SERMON_CREATE')&&<Link className='button button-primary' href='/portal/website/sermons/new'>Add Sermon</Link>}</div>
    {overview.data&&<div className='metric-grid'>{[['Published',overview.data.counts.PUBLISHED||0],['Drafts',overview.data.counts.DRAFT||0],['Processing',(overview.data.counts.PROCESSING||0)],['Scheduled',overview.data.counts.SCHEDULED||0],['Series',overview.data.series]].map(([label,count])=><Card key={label}><p className='muted'>{label}</p><strong className='metric-value'>{count}</strong></Card>)}</div>}
    {overview.data?.recent_uploads.length? <Card className='sermon-recent-uploads'><h2>Recent Uploads</h2><div>{overview.data.recent_uploads.map(asset=><Link key={asset.id} href={'/portal/website/sermons/'+asset.sermon_id}><strong>{asset.sermon_title}</strong><span>{asset.media_type} · {asset.original_filename} · {asset.processing_status}</span></Link>)}</div></Card>:null}
    <nav className='sermon-cms-tabs' aria-label='Sermon management'><Button variant={tab==='sermons'?'primary':'secondary'} onClick={()=>setTab('sermons')}>Messages</Button>{user?.permissions.includes('SERMON_MANAGE_SERIES')&&<Button variant={tab==='series'?'primary':'secondary'} onClick={()=>setTab('series')}>Series</Button>}{user?.permissions.includes('SERMON_MANAGE_CATEGORIES')&&<Button variant={tab==='categories'?'primary':'secondary'} onClick={()=>setTab('categories')}>Categories</Button>}</nav>
    {tab!=='sermons'?<TaxonomyManager kind={tab}/>:<><form className='sermon-cms-filters' onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);filters.update({search:String(data.get('search')||''),page:'1'});}}><label>Search sermons<Input name='search' defaultValue={filters.params.get('search')||''} placeholder='Title or speaker'/></label><label>Status<select aria-label='Sermon status' defaultValue={filters.params.get('status')||'ALL'} onChange={event=>filters.update({status:event.target.value,page:'1'})}>{statuses.map(status=><option key={status}>{status}</option>)}</select></label><Button type='submit'>Search</Button></form><RecordState {...list}/>{list.data&&<>{!list.data.items.length?<Empty title='No sermons yet. Add the first sermon.'>Create a draft, then attach HOPFAN-authorized media.</Empty>:<div className='sermon-cms-list'>{list.data.items.map(row=><Card className='sermon-cms-row' key={row.id}><div className='sermon-cms-thumb'>{row.assets.find(asset=>asset.media_type==='THUMBNAIL'&&asset.processing_status==='READY')?<img src={api.sermonMediaUrl(row.assets.find(asset=>asset.media_type==='THUMBNAIL'&&asset.processing_status==='READY')!.preview_url)} alt={'Thumbnail: '+row.title}/>:<Play size={30} aria-hidden='true'/>}</div><div className='sermon-cms-row-copy'><Badge tone={row.status==='PUBLISHED'?'green':row.status==='FAILED'?'neutral':'neutral'}>{row.status}</Badge><h2><Link href={'/portal/website/sermons/'+row.id}>{row.title}</Link></h2><p>{row.metadata.speaker_name} · {row.metadata.sermon_date} · {row.metadata.visibility.replaceAll('_',' ')}</p><div className='sermon-cms-badges'>{row.metadata.video_source_type==='YOUTUBE'||row.metadata.video_source_type==='VIMEO'?<Badge>{row.metadata.video_source_type}</Badge>:row.assets.some(asset=>asset.media_type==='VIDEO'&&asset.processing_status==='READY')&&<Badge>VIDEO</Badge>}{row.assets.some(asset=>asset.media_type==='AUDIO'&&asset.processing_status==='READY')&&<Badge>AUDIO</Badge>}{row.assets.some(asset=>asset.processing_status==='READY'&&asset.download_allowed&&((asset.id===row.metadata.audio_asset_id&&row.metadata.allow_audio_download)||(asset.id===row.metadata.video_asset_id&&row.metadata.allow_video_download)))&&<Badge>DOWNLOADABLE</Badge>}{row.has_unpublished_changes&&row.status==='PUBLISHED'&&<Badge>Unpublished edits</Badge>}</div>{row.metadata.series_id&&<p>Series: {options.data?.series.find(item=>item.id===row.metadata.series_id)?.name||'Linked series'}</p>}{user?.permissions.includes('SERMON_VIEW_ANALYTICS')&&<p>{(row.metrics.VIDEO_PLAY||0)+(row.metrics.AUDIO_PLAY||0)} plays · {(row.metrics.VIDEO_DOWNLOAD||0)+(row.metrics.AUDIO_DOWNLOAD||0)} downloads</p>}</div><Link className='button button-secondary' href={'/portal/website/sermons/'+row.id}>Manage Sermon</Link></Card>)}</div>}<Pagination {...list.data} change={page=>filters.update({page:String(page)})}/></>}</>}
  </>;
}
const mediaFields=['video_asset_id','audio_asset_id','thumbnail_asset_id','caption_asset_id','transcript_asset_id','document_asset_id','video_source_type','external_video_url'] as const;
export function SermonEditor({id}:{id?:string}){const{user}=useAuth();const allowed=!!user?.permissions.includes(id?'SERMON_VIEW':'SERMON_CREATE');const record=useResource(id&&allowed?'/api/v1/sermons/'+id:null,parseSermon);const options=useResource(allowed?'/api/v1/sermons/options':null,parseOptions);
  if(!allowed)return<AccessDenied/>;if(id&&!record.data)return<RecordState {...record}/>;if(!options.data)return<RecordState {...options}/>;
  return<EditorForm key={id||'new'} initial={record.data||null} options={options.data}/>;
}
function EditorForm({initial,options}:{initial:SermonRecord|null;options:ReturnType<typeof parseOptions>}){const{user}=useAuth(),router=useRouter();const[live,setLive]=useState(initial),[form,setForm]=useState<SermonMetadata>(initial?.metadata||{...emptyMetadata,sermon_date:new Date().toISOString().slice(0,10)}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[scheduled,setScheduled]=useState(''),[removing,setRemoving]=useState<PrivateAsset|null>(null);
  const liveId=live?.id;const[slugChanged,setSlugChanged]=useState(false);const[tagsText,setTagsText]=useState(form.tags.join(', '));
  const queued=!!live?.assets.some(asset=>['QUEUED','PROCESSING','UPLOADED'].includes(asset.processing_status));
  async function refresh(){if(!live)return;const latest=await api.get('/api/v1/sermons/'+live.id,parseSermon);setLive(latest);setForm(previous=>{const next={...previous};for(const field of mediaFields)Object.assign(next,{[field]:latest.metadata[field]});return next;});}
  useEffect(()=>{if(!queued||!liveId)return;let active=true;const timer=setInterval(()=>{void api.get('/api/v1/sermons/'+liveId,parseSermon).then(latest=>{if(active)setLive(latest);}).catch(()=>{});},2000);return()=>{active=false;clearInterval(timer);};},[queued,liveId]);
  async function publicationVersion(){return live&&!user?.permissions.includes('SERMON_EDIT')?live:save();}
  async function save(){const result=await api.mutate('/api/v1/sermons'+(live?'/'+live.id:''),{...form,expected_updated_at:live?.updated_at||null},parseSermon,live?'PATCH':'POST');setLive(result);setMessage('Draft saved.');if(!live)router.replace('/portal/website/sermons/'+result.id);return result;}
  function field(key:keyof SermonMetadata,label:string,type='text',required=false){
    return<label>{label}<Input type={type} value={String(form[key]??'')} required={required} readOnly={key==='slug'&&!!live?.published_at} onChange={event=>{
      const value=event.target.value;if(key==='slug')setSlugChanged(true);
      setForm(previous=>{const next={...previous,[key]:value};if(key==='title'&&!live&&!slugChanged)next.slug=value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return next;});
    }}/></label>;
  }
  return<><div className='page-heading'><div><p className='eyebrow'>SERMON EDITOR</p><h1>{live?'Manage Sermon':'Add Sermon'}</h1><p>Metadata and media share one record. Save your draft before attaching files.</p></div><Link className='button button-secondary' href='/portal/website/sermons'>Back to Sermons</Link></div>{live&&<div className='sermon-cms-status'><Badge tone={live.status==='PUBLISHED'?'green':'neutral'}>{live.status}</Badge>{live.scheduled_publish_at&&<span>Scheduled: {new Date(live.scheduled_publish_at).toLocaleString()}</span>}{live.status==='PUBLISHED'&&live.metadata.visibility==='PUBLIC'&&<Link href={'/sermons/'+live.slug} target='_blank' rel='noopener noreferrer'>Open published sermon</Link>}</div>}
    <form className='operational-form sermon-editor' onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');setMessage('');try{await save();}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}}>
      <Card><h2>Basic Information</h2><div className='form-grid'>{field('title','Title','text',true)}{field('slug','Public URL name','text',true)}{field('speaker_name','Speaker name','text',true)}{field('sermon_date','Sermon date','date',true)}{field('subtitle','Subtitle')}{field('scripture_reference','Scripture reference')}</div><label>Short description<textarea value={form.short_description} rows={3} maxLength={2000} onChange={event=>setForm({...form,short_description:event.target.value})}/></label><label>Description<textarea value={form.description} rows={6} maxLength={50000} onChange={event=>setForm({...form,description:event.target.value})}/></label></Card>
      <Card><h2>Organization</h2><div className='form-grid'><label>Series<select aria-label='Sermon series' value={form.series_id||''} onChange={event=>setForm({...form,series_id:event.target.value||null})}><option value=''>No series</option>{options.series.map(item=><option key={item.id} value={item.id}>{item.name} · {item.status}</option>)}</select></label><label>Category<select aria-label='Sermon category' value={form.category_id||''} onChange={event=>setForm({...form,category_id:event.target.value||null})}><option value=''>No category</option>{options.categories.map(item=><option key={item.id} value={item.id}>{item.name} · {item.status}</option>)}</select></label><label>Ministry<select aria-label='Sermon ministry' value={form.ministry_id||''} onChange={event=>setForm({...form,ministry_id:event.target.value||null})}><option value=''>No ministry</option>{options.ministries.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{field('service_type','Service or programme type')}<label>Approved speaker profile<select aria-label='Approved speaker profile' value={form.speaker_profile_slug} onChange={event=>setForm({...form,speaker_profile_slug:event.target.value})}><option value=''>Guest or unlinked speaker</option>{options.speaker_profiles.map(item=><option key={item.slug} value={item.slug}>{item.name}</option>)}</select></label></div><label>Tags, separated by commas<Input value={tagsText} onChange={event=>{setTagsText(event.target.value);setForm({...form,tags:event.target.value.split(',').map(value=>value.trim()).filter(Boolean)});}}/></label><label>Transcript text (optional)<textarea rows={6} value={form.transcript} maxLength={100000} onChange={event=>setForm({...form,transcript:event.target.value})}/></label></Card>
      <Card><h2>Media Sources</h2><div className='form-grid'><label>Video source<select aria-label='Video source' value={form.video_source_type} onChange={event=>setForm({...form,video_source_type:event.target.value,video_asset_id:event.target.value==='UPLOADED'?form.video_asset_id:null,external_video_url:event.target.value==='UPLOADED'||event.target.value==='NONE'?'':form.external_video_url})}>{['NONE','UPLOADED','YOUTUBE','VIMEO','EXTERNAL'].map(value=><option key={value}>{value}</option>)}</select></label>{['YOUTUBE','VIMEO','EXTERNAL'].includes(form.video_source_type)&&field('external_video_url','External video URL')}{field('external_audio_url','Approved external audio URL')}<label>Approved website thumbnail<select aria-label='Approved website thumbnail' value={form.thumbnail_media_id||''} onChange={event=>setForm({...form,thumbnail_media_id:event.target.value||null,thumbnail_asset_id:event.target.value?null:form.thumbnail_asset_id})}><option value=''>Use an attached thumbnail</option>{options.approved_images.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>{live&&<div className='form-grid'>{([['video_asset_id','VIDEO'],['audio_asset_id','AUDIO'],['thumbnail_asset_id','THUMBNAIL'],['caption_asset_id','CAPTION'],['transcript_asset_id','TRANSCRIPT'],['document_asset_id','DOCUMENT']] as const).map(([field,kind])=><label key={field}>Selected {kind.toLowerCase()}<select aria-label={'Selected '+kind.toLowerCase()} value={form[field]||''} onChange={event=>setForm({...form,[field]:event.target.value||null,...(kind==='VIDEO'&&event.target.value?{video_source_type:'UPLOADED',external_video_url:''}:{}),...(kind==='THUMBNAIL'&&event.target.value?{thumbnail_media_id:null}:{})})}><option value=''>None</option>{live.assets.filter(asset=>asset.media_type===kind&&asset.processing_status==='READY').map(asset=><option key={asset.id} value={asset.id}>{asset.original_filename}</option>)}</select></label>)}</div>}<p className='muted'>External media hosts must be approved on the backend. YouTube/Vimeo media is embedded; its files are not downloaded or extracted.</p></Card>
      <Card><h2>Publishing</h2><label>Visibility<select aria-label='Sermon visibility' value={form.visibility} onChange={event=>setForm({...form,visibility:event.target.value as SermonMetadata['visibility']})}><option value='PRIVATE'>Private</option><option value='PORTAL_ONLY'>Portal only</option><option value='PUBLIC'>Public</option></select></label><div className='live-actions'>{(['featured','allow_audio_download','allow_video_download'] as const).map(key=><label className='checkbox-label' key={key}><input type='checkbox' checked={form[key]} onChange={event=>setForm({...form,[key]:event.target.checked})}/>{key==='featured'?'Featured message':key==='allow_audio_download'?'Allow Audio Download':'Allow Video Download'}</label>)}</div><div className='form-grid'>{field('seo_title','Search and sharing title')}{field('seo_description','Search and sharing description')}</div><p className='muted'>Download flags apply only to ready HOPFAN-hosted assets which separately permit distribution.</p></Card>
      {error&&<ErrorMessage message={error}/>} {message&&<p role='status'>{message}</p>}<div className='live-actions'><Button type='submit' disabled={busy||live?.status==='SCHEDULED'||!user?.permissions.includes(live?'SERMON_EDIT':'SERMON_CREATE')}>{busy?'Saving…':'Save Draft'}</Button>{live&&user?.permissions.includes('SERMON_PUBLISH')&&<Button type='button' disabled={busy||queued||live.status==='SCHEDULED'} onClick={async()=>{setBusy(true);setError('');try{const saved=await publicationVersion();setLive(await api.mutate('/api/v1/sermons/'+saved.id+'/actions/publish',{expected_updated_at:saved.updated_at},parseSermon));setMessage('Sermon published.');}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}}>Publish Sermon</Button>}{live&&user?.permissions.includes('SERMON_ARCHIVE')&&['PUBLISHED','SCHEDULED'].includes(live.status)&&<Button type='button' variant='secondary' disabled={busy} onClick={async()=>{try{setLive(await api.mutate('/api/v1/sermons/'+live.id+'/actions/'+(live.status==='SCHEDULED'?'cancel-schedule':'unpublish'),{expected_updated_at:live.updated_at},parseSermon));}catch(error){setError(errorMessage(error));}}}>{live.status==='SCHEDULED'?'Cancel Schedule':'Unpublish'}</Button>}{live&&user?.permissions.includes('SERMON_ARCHIVE')&&<Button type='button' variant='ghost' onClick={async()=>{try{setLive(await api.mutate('/api/v1/sermons/'+live.id+'/actions/archive',{expected_updated_at:live.updated_at},parseSermon));setMessage('Sermon archived.');}catch(error){setError(errorMessage(error));}}}>Archive</Button>}</div>
      {live&&user?.permissions.includes('SERMON_PUBLISH')&&<Card><h2>Schedule Publication</h2><label>Publication date and time<Input type='datetime-local' value={scheduled} onChange={event=>setScheduled(event.target.value)}/></label><Button type='button' variant='secondary' disabled={!scheduled||busy||queued||live.status==='SCHEDULED'} onClick={async()=>{setBusy(true);setError('');try{const saved=await publicationVersion();setLive(await api.mutate('/api/v1/sermons/'+saved.id+'/actions/schedule',{expected_updated_at:saved.updated_at,scheduled_publish_at:new Date(scheduled).toISOString()},parseSermon));setMessage('Publication scheduled.');}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}}>Schedule Sermon</Button></Card>}
    </form>
    {live&&<Card className='sermon-assets'><h2>Attached Media</h2>{user?.permissions.includes('SERMON_UPLOAD_MEDIA')&&<SermonUpload sermonId={live.id} options={options} completed={refresh}/>}<div className='sermon-asset-list'>{live.assets.map(asset=><article key={asset.id}><div><strong>{asset.original_filename}</strong><p>{asset.media_type} · {fileSize(asset.file_size)} · {asset.quality_label}</p><Badge tone={asset.processing_status==='READY'?'green':asset.processing_status==='FAILED'?'neutral':'neutral'}>{asset.processing_status}</Badge>{asset.error_summary&&<p className='error-message'>{asset.error_summary}</p>}</div>{asset.processing_status==='READY'&&<div className='sermon-asset-preview'>{asset.media_type==='THUMBNAIL'?<img src={api.sermonMediaUrl(asset.preview_url)} alt='Uploaded sermon thumbnail'/>:asset.media_type==='AUDIO'?<audio controls preload='none' src={api.sermonMediaUrl(asset.preview_url)}/>:asset.media_type==='VIDEO'?<video controls preload='none' src={api.sermonMediaUrl(asset.preview_url)}/>:<a href={api.sermonMediaUrl(asset.preview_url)} target='_blank' rel='noopener noreferrer'>Preview document</a>}</div>}<div className='live-actions'>{user?.permissions.includes('SERMON_EDIT')&&<label className='checkbox-label'><input type='checkbox' checked={asset.download_allowed} onChange={async event=>{try{await api.mutate('/api/v1/sermons/'+live.id+'/media/'+asset.id+'/permissions',{expected_updated_at:asset.updated_at,download_allowed:event.target.checked},value=>value);await refresh();}catch(error){setError(errorMessage(error));}}}/>Asset download permission</label>}{asset.processing_status==='FAILED'&&user?.permissions.includes('SERMON_UPLOAD_MEDIA')&&<Button type='button' variant='secondary' onClick={async()=>{try{await api.mutate('/api/v1/sermons/'+live.id+'/media/'+asset.id+'/retry',{},value=>value);await refresh();}catch(error){setError(errorMessage(error));}}}>Retry Inspection</Button>}{user?.permissions.includes('SERMON_DELETE_MEDIA')&&<Button type='button' variant='ghost' disabled={['QUEUED','PROCESSING'].includes(asset.processing_status)} onClick={()=>setRemoving(asset)}>Delete Media</Button>}</div></article>)}</div></Card>}
    {live&&user?.permissions.includes('SERMON_VIEW_ANALYTICS')&&<Card className='sermon-analytics'><h2>Real Playback & Downloads</h2><p>Hosted plays are recorded after ten seconds. External provider playback is not estimated.</p><div className='live-actions'>{Object.entries(live.metrics).map(([key,count])=><Badge key={key}>{key.replaceAll('_',' ')}: {count}</Badge>)}</div></Card>}
    {removing&&live&&<OperationalModal title='Delete sermon media' description='A published or scheduled asset must be replaced or unpublished first. This action removes the stored file after backend reference checks.' close={()=>setRemoving(null)}><p>{removing.original_filename}</p><Button onClick={async()=>{try{await api.mutate('/api/v1/sermons/'+live.id+'/media/'+removing.id+'/delete',{expected_updated_at:live.updated_at,confirmed:true},value=>value);setRemoving(null);await refresh();}catch(error){setError(errorMessage(error));setRemoving(null);}}}>Confirm Delete</Button></OperationalModal>}
  </>;
}
function TaxonomyManager({kind}:{kind:'series'|'categories'}){const{user}=useAuth();const resource=useResource('/api/v1/sermon-'+kind,parseTaxonomies);const options=useResource('/api/v1/sermons/options',parseOptions);const[editing,setEditing]=useState<TaxonomyRecord|'new'|null>(null),[error,setError]=useState('');const allowed=user?.permissions.includes(kind==='series'?'SERMON_MANAGE_SERIES':'SERMON_MANAGE_CATEGORIES');
  if(!allowed)return<AccessDenied/>;
  return<><div className='page-heading'><h2>{kind==='series'?'Sermon Series':'Sermon Categories'}</h2><Button onClick={()=>setEditing('new')}>Add {kind==='series'?'Series':'Category'}</Button></div>{error&&<ErrorMessage message={error}/>}<RecordState {...resource}/>{resource.data?.map(row=><Card key={row.id} className='cms-content-row'><div><Badge>{row.status}</Badge><h3>{row.name}</h3><p>{row.description}</p></div><div className='live-actions'><Button variant='secondary' onClick={()=>setEditing(row)}>Edit</Button>{user?.permissions.includes('SERMON_PUBLISH')&&<Button onClick={async()=>{try{await api.mutate('/api/v1/sermon-'+kind+'/'+row.id+'/publish',{expected_updated_at:row.updated_at},parseTaxonomy);resource.retry();}catch(error){setError(errorMessage(error));}}}>Publish</Button>}<Button variant='ghost' onClick={async()=>{try{await api.mutate('/api/v1/sermon-'+kind+'/'+row.id+'/archive',{expected_updated_at:row.updated_at},parseTaxonomy);resource.retry();}catch(error){setError(errorMessage(error));}}}>Archive</Button></div></Card>)}{editing&&<OperationalModal title={editing==='new'?'Add collection':'Edit collection'} description='Collection drafts require publication before their public page is available.' close={()=>setEditing(null)}><form className='operational-form' onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{await api.mutate('/api/v1/sermon-'+kind+(editing==='new'?'':'/'+editing.id),{name:String(form.get('name')||''),slug:String(form.get('slug')||''),description:String(form.get('description')||''),display_order:Number(form.get('display_order')||0),cover_image_id:String(form.get('cover_image_id')||'')||null,expected_updated_at:editing==='new'?null:editing.updated_at},parseTaxonomy,editing==='new'?'POST':'PATCH');setEditing(null);resource.retry();}catch(error){setError(errorMessage(error));}}}><label>Name<Input name='name' required defaultValue={editing==='new'?'':editing.name}/></label><label>Public URL name<Input name='slug' required readOnly={editing!=='new'&&!!editing.published_at} defaultValue={editing==='new'?'':editing.slug}/></label><label>Description<textarea name='description' rows={4} defaultValue={editing==='new'?'':editing.description}/></label><label>Display order<Input name='display_order' type='number' min={0} defaultValue={editing==='new'?0:editing.display_order}/></label><label>Approved collection artwork<select name='cover_image_id' defaultValue={editing==='new'?'':editing.cover_image_id||''}><option value=''>No cover image</option>{options.data?.approved_images.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Button type='submit'>Save Collection Draft</Button></form></OperationalModal>}</>;
}
