import {obj,str,num,bool,array,nullable,parsePage} from '@/lib/api/workspace';
import type {SermonRecord,SermonMetadata,PrivateAsset,MediaKind} from './types';
export const emptyMetadata:SermonMetadata={title:'',slug:'',subtitle:'',description:'',short_description:'',sermon_date:'',speaker_name:'',speaker_member_id:null,speaker_profile_slug:'',scripture_reference:'',series_id:null,category_id:null,ministry_id:null,service_type:'',tags:[],transcript:'',thumbnail_media_id:null,visibility:'PRIVATE',featured:false,video_source_type:'NONE',external_video_url:'',external_audio_url:'',video_asset_id:null,audio_asset_id:null,thumbnail_asset_id:null,caption_asset_id:null,transcript_asset_id:null,document_asset_id:null,allow_audio_download:false,allow_video_download:false,seo_title:'',seo_description:''};
export function parsePrivateAsset(value:unknown):PrivateAsset{const o=obj(value);return{id:str(o.id),media_type:str(o.media_type) as MediaKind,mime_type:str(o.mime_type),file_size:num(o.file_size),duration_seconds:nullable(o.duration_seconds,num),width:nullable(o.width,num),height:nullable(o.height,num),quality_label:str(o.quality_label),original_filename:str(o.original_filename),format:str(o.format),download_allowed:bool(o.download_allowed),processing_status:str(o.processing_status),error_summary:str(o.error_summary),updated_at:str(o.updated_at),preview_url:str(o.preview_url)};}
export function parseSermon(value:unknown):SermonRecord{const o=obj(value),m=obj(o.metadata),metadata={...emptyMetadata};for(const key of Object.keys(emptyMetadata) as (keyof SermonMetadata)[]){const original=emptyMetadata[key],value=m[key];if(Array.isArray(original))Object.assign(metadata,{[key]:array(value,str)});else if(original===null)Object.assign(metadata,{[key]:nullable(value,str)});else if(typeof original==='boolean')Object.assign(metadata,{[key]:bool(value)});else Object.assign(metadata,{[key]:str(value)});}const raw=obj(o.metrics),metrics:Record<string,number>={};for(const key of ['VIDEO_PLAY','AUDIO_PLAY','VIDEO_DOWNLOAD','AUDIO_DOWNLOAD'])if(key in raw)metrics[key]=num(raw[key]);return{id:str(o.id),title:str(o.title),slug:str(o.slug),status:str(o.status),metadata,updated_at:str(o.updated_at),published_at:nullable(o.published_at,str),has_unpublished_changes:bool(o.has_unpublished_changes),assets:array(o.assets,parsePrivateAsset),metrics,scheduled_publish_at:nullable(o.scheduled_publish_at,str)};}
export const parseSermons=parsePage(parseSermon);
export interface SermonOptions {ministries:{id:string;name:string}[];approved_images:{id:string;name:string}[];series:{id:string;name:string;status:string}[];categories:{id:string;name:string;status:string}[];speaker_profiles:{slug:string;name:string}[];limits:Record<string,number>;allowed_extensions:Record<string,string[]>}
export function parseOptions(value:unknown):SermonOptions{const o=obj(value),limits=obj(o.limits),extensions=obj(o.allowed_extensions);const result:SermonOptions={ministries:array(o.ministries,value=>{const o=obj(value);return{id:str(o.id),name:str(o.name)}}),approved_images:array(o.approved_images,value=>{const o=obj(value);return{id:str(o.id),name:str(o.name)}}),series:array(o.series,value=>{const o=obj(value);return{id:str(o.id),name:str(o.name),status:str(o.status)}}),categories:array(o.categories,value=>{const o=obj(value);return{id:str(o.id),name:str(o.name),status:str(o.status)}}),speaker_profiles:array(o.speaker_profiles,value=>{const o=obj(value);return{slug:str(o.slug),name:str(o.name)}}),limits:{},allowed_extensions:{}};for(const key of ['VIDEO','AUDIO','THUMBNAIL','CAPTION','TRANSCRIPT','DOCUMENT']){result.limits[key]=num(limits[key]);result.allowed_extensions[key]=array(extensions[key],str);}return result;}
export function parseOverview(value:unknown){const o=obj(value),counts=obj(o.counts);const result:Record<string,number>={};for(const key of Object.keys(counts))result[key]=num(counts[key]);return{counts:result,series:num(o.series),categories:num(o.categories),recent_uploads:array(o.recent_uploads,value=>{const o=obj(value);return{...parsePrivateAsset(o),sermon_id:str(o.sermon_id),sermon_title:str(o.sermon_title)}})};}
export interface TaxonomyRecord {id:string;name:string;slug:string;description:string;cover_image_id:string|null;status:string;display_order:number;updated_at:string;published_at:string|null}
export function parseTaxonomy(value:unknown):TaxonomyRecord{const o=obj(value);return{id:str(o.id),name:str(o.name),slug:str(o.slug),description:str(o.description),cover_image_id:nullable(o.cover_image_id,str),status:str(o.status),display_order:num(o.display_order),updated_at:str(o.updated_at),published_at:nullable(o.published_at,str)};}
export const parseTaxonomies=(value:unknown)=>array(value,parseTaxonomy);
