import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Play,Headphones,ArrowRight,Search} from 'lucide-react';
import {getPublic,publicImageUrl,canonicalOrigin,jsonLd,type PublicPage} from '@/features/public/server';
import {PublicPhoto} from '@/features/public/public-photo';
import {SermonPlayer} from './player';
import {duration,type Sermon,type Filters,type Collection} from './types';
const apiOrigin=process.env.PUBLIC_API_ORIGIN??process.env.NEXT_PUBLIC_API_BASE_URL??'http://localhost:8000';
function mediaUrl(path:string|null){return path&&/^\/api\/v1\/public\/sermons\/[a-z0-9-]+\/(?:media\/[a-f0-9-]{36}|download\/[a-z]+)$/.test(path)?apiOrigin+path:'';}
function hydrated(item:Sermon):Sermon{return {...item,image:item.image?{...item.image,url:publicImageUrl(item.image)}:null,media:item.media.map(asset=>({...asset,url:mediaUrl(asset.url),download_url:asset.download_url?mediaUrl(asset.download_url):null}))};}
function date(value:string){return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z'));}
export function SermonCard({item,compact=false}:{item:Sermon;compact?:boolean}){
  const video=!!(item.video_embed_url||item.external_video_url||item.media.some(asset=>asset.media_type==='VIDEO')),audio=!!(item.audio_url||item.media.some(asset=>asset.media_type==='AUDIO'));
  return<article className={'sermon-card '+(compact?'sermon-card-compact':'')}><Link className='sermon-thumb' href={'/sermons/'+item.slug} aria-label={'Open sermon: '+item.title}><PublicPhoto image={item.image?{...item.image,url:publicImageUrl(item.image)}:null} sizes={compact?'200px':'(max-width:650px) 100vw, (max-width:1050px) 50vw, 420px'}/>{item.duration_seconds&&<span className='sermon-duration'>{duration(item.duration_seconds)}</span>}</Link><div className='sermon-card-copy'><h3><Link href={'/sermons/'+item.slug}>{item.title}</Link></h3><p>{item.speaker}</p><p><time dateTime={item.sermon_date}>{date(item.sermon_date)}</time>{item.views>0?' · '+item.views.toLocaleString()+' plays':''}</p>{item.series&&<p className='sermon-card-series'>{item.series}</p>}<div className='sermon-media-badges'>{video&&<span><Play size={13} aria-hidden='true'/>Video</span>}{audio&&<span><Headphones size={13} aria-hidden='true'/>Audio</span>}</div></div></article>;
}
export async function SermonLibrary({searchParams,collection}:{searchParams:Promise<Record<string,string|undefined>>;collection?:Collection}){
  const query=await searchParams;const params=new URLSearchParams({page_number:query.page||'1',page_size:'24',search:query.search||'',series:collection?.id||query.series||'',speaker:query.speaker||'',category:query.category||'',media_type:query.media_type||'',sort:query.sort||'latest'});if(query.year)params.set('year',query.year);
  const[data,filters,featured]=await Promise.all([getPublic<PublicPage<Sermon>>('sermons?'+params),getPublic<Filters>('sermons/filters'),collection?Promise.resolve(null):getPublic<PublicPage<Sermon>>('sermons?sort=featured&page_size=1')]);
  const latest=featured?.items[0];
  return<section className='sermon-library public-section'><p className='public-eyebrow'>{collection?'Sermon Series':'HOPFAN Messages'}</p><h1>{collection?.name||'Messages & Sermons'}</h1><p className='sermon-library-intro'>{collection?.description||'Watch, listen and grow in the Word with messages from HOPFAN.'}</p>{collection?.image&&<div className='sermon-collection-art'><PublicPhoto image={{...collection.image,url:publicImageUrl(collection.image)}} sizes='(max-width:650px) 100vw, 720px'/></div>}
    {latest&&!query.search&&!query.page&&<div className='sermon-featured'><Link className='sermon-featured-visual' href={'/sermons/'+latest.slug} aria-label={'Open sermon: '+latest.title}><PublicPhoto image={latest.image?{...latest.image,url:publicImageUrl(latest.image)}:null} priority sizes='(max-width:760px) 100vw, 700px'/><span className='sermon-featured-play'><Play size={30} aria-hidden='true'/></span></Link><div><p className='public-eyebrow'>{latest.featured?'Featured Message':'Latest Message'}</p><h2>{latest.title}</h2><p>{latest.speaker} · {date(latest.sermon_date)}</p>{latest.summary&&<p>{latest.summary.slice(0,280)}</p>}<Link className='public-button' href={'/sermons/'+latest.slug}>{latest.media.some(asset=>asset.media_type==='VIDEO')||latest.video_embed_url?'Watch Message':'Open Message'}<ArrowRight size={18} aria-hidden='true'/></Link></div></div>}
    <form className='sermon-filters'><label className='sermon-search'>Search messages<div><Search size={19} aria-hidden='true'/><input name='search' defaultValue={query.search} placeholder='Title, speaker, scripture or topic'/></div></label>{!collection&&<label>Series<select name='series' aria-label='Series filter' defaultValue={query.series||''}><option value=''>All series</option>{filters?.series.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>Speaker<select name='speaker' aria-label='Speaker filter' defaultValue={query.speaker||''}><option value=''>All speakers</option>{filters?.speakers.map(name=><option key={name}>{name}</option>)}</select></label><label>Category<select name='category' aria-label='Category filter' defaultValue={query.category||''}><option value=''>All categories</option>{filters?.categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Year<select name='year' aria-label='Year filter' defaultValue={query.year||''}><option value=''>All years</option>{filters?.years.map(year=><option key={year}>{year}</option>)}</select></label><label>Media<select name='media_type' aria-label='Media filter' defaultValue={query.media_type||''}><option value=''>Watch or listen</option><option value='VIDEO'>Video</option><option value='AUDIO'>Audio</option></select></label><label>Order<select name='sort' aria-label='Sermon order' defaultValue={query.sort||'latest'}><option value='latest'>Latest messages</option><option value='popular'>Most played</option></select></label><button className='public-button' type='submit'>Search</button></form>
    <div className='sermon-results-heading'><h2>{collection?'Messages in this series':'Latest Sermons'}</h2>{data&&<p>{data.total} {data.total===1?'message':'messages'}</p>}</div>
    {!data?<div className='public-empty'><h2>We couldn’t load the sermon library.</h2><p>Please try again shortly.</p></div>:!data.items.length?<div className='public-empty'><h2>{query.search?'No matching messages.':'No sermons have been published yet.'}</h2><p>Check back for new messages, or try another search.</p></div>:<div className='sermon-grid'>{data.items.map(item=><SermonCard key={item.slug} item={item}/>)}</div>}
    {data&&data.pages>1&&<nav className='public-pagination' aria-label='Sermon pagination'>{data.page>1&&<Link href={'?'+new URLSearchParams({...query,page:String(data.page-1)} as Record<string,string>)}>Previous</Link>}<span>Page {data.page} of {data.pages}</span>{data.page<data.pages&&<Link href={'?'+new URLSearchParams({...query,page:String(data.page+1)} as Record<string,string>)}>Next</Link>}</nav>}
    {!collection&&filters?.series.length!==0&&filters&&<section className='sermon-series-preview'><h2>Explore Series</h2><div className='sermon-series-grid'>{filters.series.slice(0,6).map(item=><Link href={'/sermons/series/'+item.slug} key={item.id}><PublicPhoto image={item.image?{...item.image,url:publicImageUrl(item.image)}:null}/><div><h3>{item.name}</h3><p>{item.sermon_count} messages<ArrowRight size={17} aria-hidden='true'/></p></div></Link>)}</div></section>}
  </section>;
}
export async function SermonWatch({slug,mode}:{slug:string;mode?:string}){const[item,related]=await Promise.all([getPublic<Sermon>('sermons/'+encodeURIComponent(slug)),getPublic<Sermon[]>('sermons/'+encodeURIComponent(slug)+'/related')]);if(!item)notFound();const sermon=hydrated(item),canonical=canonicalOrigin()?canonicalOrigin()+'/sermons/'+slug:'';
  const nativeVideo=sermon.media.find(asset=>asset.media_type==='VIDEO'),nativeAudio=sermon.media.find(asset=>asset.media_type==='AUDIO');
  const common={'@context':'https://schema.org',name:item.title,description:item.summary||item.title,datePublished:item.published_at,...(item.duration_seconds?{duration:'PT'+item.duration_seconds+'S'}:{})};
  const structured=[...(nativeVideo||sermon.video_embed_url||sermon.external_video_url?[{...common,'@type':'VideoObject',thumbnailUrl:sermon.image?.url,uploadDate:item.published_at,contentUrl:nativeVideo?.url||sermon.external_video_url||undefined,embedUrl:sermon.video_embed_url||undefined}]:[]),...(nativeAudio?[{...common,'@type':'AudioObject',contentUrl:nativeAudio.url}]:[])];
  return<section className='public-section sermon-watch'><Link className='public-text-link' href='/sermons'>All Sermons<ArrowRight size={17} aria-hidden='true'/></Link>{structured.length>0&&<script type='application/ld+json' dangerouslySetInnerHTML={{__html:jsonLd(structured)}}/>}<div className='sermon-watch-layout'><article><SermonPlayer sermon={sermon} initialMode={mode==='audio'?'AUDIO':'VIDEO'} canonical={canonical}/><h1>{item.title}</h1>{item.subtitle&&<p className='sermon-subtitle'>{item.subtitle}</p>}<p className='sermon-byline'>{item.speaker_profile_slug?<Link href={'/leadership/'+item.speaker_profile_slug}>{item.speaker}</Link>:item.speaker} · <time dateTime={item.sermon_date}>{date(item.sermon_date)}</time>{item.views>0?' · '+item.views.toLocaleString()+' plays':''}</p><div className='sermon-description'>{item.scripture_reference&&<p><strong>Scripture:</strong> {item.scripture_reference}</p>}{item.series_info&&<p><strong>Series:</strong> <Link href={'/sermons/series/'+item.series_info.slug}>{item.series_info.name}</Link></p>}{item.category&&<p><strong>Category:</strong> {item.category.name}</p>}<p>{item.body||item.summary}</p>{item.tags.length>0&&<div className='sermon-tags'>{item.tags.map(tag=><Link key={tag} href={'/sermons?search='+encodeURIComponent(tag)}>{tag}</Link>)}</div>}</div>{item.transcript&&<details className='sermon-transcript'><summary>Read Transcript</summary><div>{item.transcript}</div></details>}</article><aside className='sermon-related'><h2>Up Next</h2>{related?.length?related.map(next=><SermonCard key={next.slug} item={next} compact/>):<p>More messages will appear here as they are published.</p>}</aside></div></section>;
}
export async function SermonSeriesPage({slug,searchParams}:{slug:string;searchParams:Promise<Record<string,string|undefined>>}){const collection=await getPublic<Collection>('sermon-series/'+encodeURIComponent(slug));if(!collection)notFound();return<SermonLibrary searchParams={searchParams} collection={collection}/>;}
