import type {PublicContent,PublicImage} from '@/features/public/server';
export type MediaKind='VIDEO'|'AUDIO'|'THUMBNAIL'|'CAPTION'|'TRANSCRIPT'|'DOCUMENT';
export interface SermonAsset {id:string;media_type:MediaKind;mime_type:string;file_size:number;duration_seconds:number|null;width:number|null;height:number|null;quality_label:string;url:string;download_url:string|null}
export interface Sermon extends PublicContent {subtitle:string;speaker:string;sermon_date:string;series:string;series_info:{id:string;name:string;slug:string}|null;category:{id:string;name:string;slug:string}|null;tags:string[];service_type:string;featured:boolean;duration_seconds:number|null;video_source_type:string;external_video_url:string;video_embed_url:string;audio_url:string;media:SermonAsset[];transcript:string;speaker_profile_slug:string;published_at:string|null;views:number;audio_plays:number;video_plays:number}
export interface Collection {id:string;name:string;slug:string;description:string;image:PublicImage|null;sermon_count:number}
export interface Filters {series:Collection[];categories:Collection[];speakers:string[];years:number[]}
export interface SermonMetadata {title:string;slug:string;subtitle:string;description:string;short_description:string;sermon_date:string;speaker_name:string;speaker_member_id:string|null;speaker_profile_slug:string;scripture_reference:string;series_id:string|null;category_id:string|null;ministry_id:string|null;service_type:string;tags:string[];transcript:string;thumbnail_media_id:string|null;visibility:'PUBLIC'|'PORTAL_ONLY'|'PRIVATE';featured:boolean;video_source_type:string;external_video_url:string;external_audio_url:string;video_asset_id:string|null;audio_asset_id:string|null;thumbnail_asset_id:string|null;caption_asset_id:string|null;transcript_asset_id:string|null;document_asset_id:string|null;allow_audio_download:boolean;allow_video_download:boolean;seo_title:string;seo_description:string}
export interface PrivateAsset extends Omit<SermonAsset,'url'|'download_url'>{original_filename:string;format:string;download_allowed:boolean;processing_status:string;error_summary:string;updated_at:string;preview_url:string}
export interface SermonRecord {id:string;title:string;slug:string;status:string;metadata:SermonMetadata;updated_at:string;published_at:string|null;has_unpublished_changes:boolean;assets:PrivateAsset[];metrics:Record<string,number>;scheduled_publish_at:string|null}
export function duration(value:number|null|undefined){if(!value)return '';const h=Math.floor(value/3600),m=Math.floor(value%3600/60),s=Math.floor(value%60);return(h?h+':':'')+String(m).padStart(h?2:1,'0')+':'+String(s).padStart(2,'0');}
export function fileSize(bytes:number){return bytes>=1024**2?(bytes/1024**2).toFixed(1)+' MB':Math.max(1,Math.ceil(bytes/1024))+' KB';}
