import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
const api='http://localhost:8001';
async function login(page:Page,name='admin'){await page.goto('/login');await expect(page.getByLabel('Email or username')).toBeEnabled();await page.getByLabel('Email or username').fill('portal-'+name+'@example.invalid');await page.locator('input[name="password"]').fill('Portal-Synthetic!2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/portal\/dashboard/);}
test('public library is server filtered and does not preload sermon video',async({page})=>{
  const videoRequests:string[]=[];page.on('request',request=>{if(request.resourceType()==='media')videoRequests.push(request.url());});await page.goto('/sermons');await expect(page.getByRole('heading',{name:'Messages & Sermons',exact:true})).toBeVisible();await expect(page.locator('.sermon-card').filter({hasText:'Synthetic Hosted Sermon'})).toHaveCount(1);expect(videoRequests).toEqual([]);
  await page.getByLabel('Search messages',{exact:true}).fill('Synthetic Pastor');await page.getByRole('button',{name:'Search',exact:true}).click();await expect(page.locator('.sermon-card')).toHaveCount(1);
  await page.getByLabel('Series filter',{exact:true}).selectOption({label:'Synthetic Sermon Series'});await page.getByRole('button',{name:'Search',exact:true}).click();await expect(page.locator('.sermon-card')).toHaveCount(1);
  await page.getByLabel('Sermon order',{exact:true}).selectOption('popular');await page.getByRole('button',{name:'Search',exact:true}).click();await expect(page).toHaveURL(/sort=popular/);
  await page.goto('/sermons/series/synthetic-sermon-series');await expect(page.getByRole('heading',{name:'Synthetic Sermon Series',exact:true})).toBeVisible();await expect(page.locator('.sermon-collection-art img')).toBeVisible();await expect(page.locator('.sermon-card')).toHaveCount(1);
});
test('watch/listen switches one sermon and hosted playback uses controlled ranges and downloads',async({page})=>{
  await page.goto('/sermons/synthetic-hosted-sermon');await expect(page.getByRole('heading',{name:'Synthetic Hosted Sermon',exact:true})).toBeVisible();const structured=JSON.parse(await page.locator('script[type="application/ld+json"]').textContent()||'[]');expect(structured.map((item:{'@type':string})=>item['@type'])).toEqual(['VideoObject','AudioObject']);const video=page.locator('video');await expect(video).toHaveAttribute('preload','metadata');
  const record=await(await page.request.get(api+'/api/v1/public/sermons/synthetic-hosted-sermon')).json();const source=record.media.find((item:{media_type:string})=>item.media_type==='VIDEO');const ranged=await page.request.get(api+source.url,{headers:{Range:'bytes=0-127'}});expect(ranged.status()).toBe(206);expect((await ranged.body()).length).toBe(128);
  await page.getByRole('button',{name:'Listen',exact:true}).click();await expect(page.locator('audio')).toBeVisible();await expect(page.locator('video')).toHaveCount(0);
  await expect(page.getByRole('link',{name:/Download Audio/})).toBeVisible();await expect(page.getByRole('link',{name:/Download Video/})).toHaveCount(0);expect((await page.request.get(api+'/api/v1/public/sermons/synthetic-hosted-sermon/download/video')).status()).toBe(404);
  const audio=page.locator('audio');await audio.evaluate((element:HTMLAudioElement)=>{element.currentTime=11;element.dispatchEvent(new Event('timeupdate'));});await expect.poll(async()=> (await(await page.request.get(api+'/api/v1/public/sermons/synthetic-hosted-sermon')).json()).audio_plays).toBeGreaterThan(0);
});
test('CMS creates one guest sermon, uploads a thumbnail with progress and publishes an external video',async({page})=>{
  test.setTimeout(120000);await login(page);await page.goto('/portal/website/sermons');await page.getByRole('link',{name:'Add Sermon',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Browser Sermon');await page.getByLabel('Speaker name',{exact:true}).fill('Browser Guest');await page.getByLabel('Sermon date',{exact:true}).fill('2026-10-08');await page.getByLabel('Video source',{exact:true}).selectOption('YOUTUBE');await page.getByLabel('External video URL',{exact:true}).fill('https://youtu.be/dQw4w9WgXcQ');await page.getByLabel('Sermon visibility',{exact:true}).selectOption('PUBLIC');await page.getByLabel('Short description',{exact:true}).fill('A synthetic public browser message.');await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page).toHaveURL(/portal\/website\/sermons\/[a-f0-9-]{36}$/);
  await page.getByLabel('Media type',{exact:true}).selectOption('THUMBNAIL');const file=await page.request.get(api+'/_test/sermon-file/thumbnail');await page.getByLabel('Choose sermon media file',{exact:true}).setInputFiles({name:'synthetic-thumbnail.jpg',mimeType:'image/jpeg',buffer:await file.body()});await page.getByLabel(/I confirm HOPFAN owns/).check();await page.getByRole('button',{name:'Upload Media',exact:true}).click();await expect(page.getByText('synthetic-thumbnail.jpg',{exact:true}).last()).toBeVisible();await expect(page.getByText('READY',{exact:true}).last()).toBeVisible();
  await page.getByRole('button',{name:'Publish Sermon',exact:true}).click();await expect(page.getByText('Sermon published.',{exact:true})).toBeVisible();await page.goto('/sermons/browser-sermon');await expect(page.getByRole('heading',{name:'Browser Sermon',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Load YouTube Video',exact:true})).toBeVisible();await expect(page.locator('iframe')).toHaveCount(0);
  expect((await page.request.get(api+'/api/v1/sermons')).status()).toBe(200);await page.goto('/');await expect(page.getByRole('main')).toBeVisible();
});
test('unauthorized users cannot reach the sermon editor or upload APIs',async({page})=>{
  expect((await page.request.post(api+'/api/v1/sermons',{headers:{Origin:'http://localhost:3002'}})).status()).toBe(401);await login(page,'teacher');await page.goto('/portal/website/sermons');await expect(page.getByRole('heading',{name:'Access denied',exact:true})).toBeVisible();expect((await page.request.get(api+'/api/v1/sermons')).status()).toBe(403);
});
test('sermon library, watch and CMS screens are responsive and accessible',async({page})=>{
  test.setTimeout(180000);const dir=path.resolve('../docs/screenshots/sermon-platform');await fs.mkdir(dir,{recursive:true});
  for(const width of [1920,1366,768,390]){await page.setViewportSize({width,height:width===390?844:768});for(const [name,url] of [['library','/sermons'],['watch','/sermons/synthetic-hosted-sermon'],['series','/sermons/series/synthetic-sermon-series']]){await page.goto(url);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width===1366||width===390)expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag22aa']).analyze()).violations).toEqual([]);await page.screenshot({path:path.join(dir,name+'_'+width+'.png'),fullPage:true});}}
  await login(page);const fixtures=await(await page.request.get(api+'/_test/fixtures')).json();for(const width of [1366,390]){await page.setViewportSize({width,height:width===390?844:768});for(const [name,url] of [['cms','/portal/website/sermons'],['editor','/portal/website/sermons/new'],['edit','/portal/website/sermons/'+fixtures.sermon_id]]){await page.goto(url);await expect(page.getByRole('heading',{name:name==='cms'?'Sermons':name==='editor'?'Add Sermon':'Manage Sermon',exact:true})).toBeVisible();if(name==='cms'){await expect(page.locator('.sermon-cms-row').filter({hasText:'Synthetic Hosted Sermon'})).toBeVisible();await expect(page.getByText('Published',{exact:true})).toBeVisible();}else{await expect(page.getByLabel('Sermon ministry',{exact:true})).toBeVisible();}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag22aa']).analyze()).violations).toEqual([]);await page.screenshot({path:path.join(dir,name+'_'+width+'.png'),fullPage:true});}}
});
