"""create attendance sessions and records

Revision ID: 3e58beb20ec4
Revises: 06fd8fecd7a3
Create Date: 2026-10-05 09:53:36.728664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e58beb20ec4'
down_revision: Union[str, Sequence[str], None] = '06fd8fecd7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('session_type', sa.Enum('SUNDAY_SERVICE', 'MINISTRY_MEETING', 'SUNDAY_SCHOOL', 'SPECIAL_EVENT', name='attendance_session_type', native_enum=False), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('ministry_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Enum('OPEN', 'CLOSED', name='attendance_session_state', native_enum=False), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sessions_ministry_id'), 'attendance_sessions', ['ministry_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_session_date'), 'attendance_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_session_type'), 'attendance_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_state'), 'attendance_sessions', ['state'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'LATE', 'EXCUSED', 'ABSENT', name='attendance_status', native_enum=False), nullable=False),
    sa.Column('marked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'member_id', name='uq_attendance_session_member')
    )
    op.create_index(op.f('ix_attendance_records_member_id'), 'attendance_records', ['member_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_status'), 'attendance_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_status'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_member_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_attendance_sessions_state'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_session_type'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_session_date'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_ministry_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###
