"""Upgrade attendance lifecycle scopes rosters and audit

Revision ID: 4837e2db4cfd
Revises: 3e58beb20ec4
Create Date: 2026-10-05 10:36:58.078121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import json
import uuid


# revision identifiers, used by Alembic.
revision: str = '4837e2db4cfd'
down_revision: Union[str, Sequence[str], None] = '3e58beb20ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('ministry_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_audit_logs_target_user_id'), 'authorization_audit_logs', ['target_user_id'], unique=False)
    op.create_table('user_ministry_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ministry_id', sa.UUID(), nullable=False),
    sa.Column('can_view_attendance', sa.Boolean(), nullable=False),
    sa.Column('can_create_attendance', sa.Boolean(), nullable=False),
    sa.Column('can_record_attendance', sa.Boolean(), nullable=False),
    sa.Column('can_correct_attendance', sa.Boolean(), nullable=False),
    sa.Column('can_close_attendance', sa.Boolean(), nullable=False),
    sa.Column('can_view_reports', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ministry_id', name='uq_user_ministry_scope')
    )
    op.create_index(op.f('ix_user_ministry_scopes_ministry_id'), 'user_ministry_scopes', ['ministry_id'], unique=False)
    op.create_index(op.f('ix_user_ministry_scopes_user_id'), 'user_ministry_scopes', ['user_id'], unique=False)
    op.create_table('attendance_roster_members',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id', 'member_id')
    )
    op.create_index(op.f('ix_attendance_roster_members_member_id'), 'attendance_roster_members', ['member_id'], unique=False)
    op.create_table('attendance_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attendance_record_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_audit_logs_attendance_record_id'), 'attendance_audit_logs', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_attendance_audit_logs_changed_at'), 'attendance_audit_logs', ['changed_at'], unique=False)
    op.create_index(op.f('ix_attendance_audit_logs_changed_by_user_id'), 'attendance_audit_logs', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_attendance_audit_logs_member_id'), 'attendance_audit_logs', ['member_id'], unique=False)
    op.create_index(op.f('ix_attendance_audit_logs_session_id'), 'attendance_audit_logs', ['session_id'], unique=False)
    op.add_column('attendance_records', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('attendance_records', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key('fk_attendance_records_updated_by_user_id', 'attendance_records', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('attendance_sessions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('scope_type', sa.Enum('GLOBAL', 'MINISTRY', name='attendance_scope_type', native_enum=False), nullable=True))
    op.add_column('attendance_sessions', sa.Column('roster_type', sa.Enum('WHOLE_CHURCH', 'ALL_MINISTRY_MEMBERS', 'SELECTED_MEMBERS', 'EXECUTIVES', name='attendance_roster_type', native_enum=False), nullable=True))
    op.add_column('attendance_sessions', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendance_sessions', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendance_sessions', sa.Column('closed_by_user_id', sa.UUID(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendance_sessions', sa.Column('locked_by_user_id', sa.UUID(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendance_sessions', sa.Column('reopened_by_user_id', sa.UUID(), nullable=True))
    op.alter_column('attendance_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('SUNDAY_SERVICE', 'MINISTRY_MEETING', 'SUNDAY_SCHOOL', 'SPECIAL_EVENT', 'PRAYER_MEETING', 'CHURCH_MEETING', 'LEADERSHIP_MEETING', 'OTHER', name='attendance_session_type', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_attendance_sessions_scope_type'), 'attendance_sessions', ['scope_type'], unique=False)
    op.create_foreign_key('fk_attendance_sessions_reopened_by_user_id', 'attendance_sessions', 'users', ['reopened_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_attendance_sessions_closed_by_user_id', 'attendance_sessions', 'users', ['closed_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_attendance_sessions_locked_by_user_id', 'attendance_sessions', 'users', ['locked_by_user_id'], ['id'], ondelete='SET NULL')
    # Reviewed forward migration: backfill first, then enforce the new invariants.
    # Existing names, IDs, status values, markers and timestamps are unchanged.
    op.execute("""UPDATE attendance_sessions SET
        scope_type = CASE WHEN ministry_id IS NULL THEN 'GLOBAL' ELSE 'MINISTRY' END,
        roster_type = CASE WHEN ministry_id IS NULL THEN 'WHOLE_CHURCH' ELSE 'ALL_MINISTRY_MEMBERS' END,
        opened_at = created_at,
        closed_at = CASE WHEN state = 'CLOSED' THEN updated_at ELSE NULL END""")
    op.execute("UPDATE attendance_records SET updated_at = marked_at")
    # Fail safely rather than silently rewriting a pre-existing ministry Sunday.
    bind = op.get_bind()
    if bind.execute(sa.text("SELECT count(*) FROM attendance_sessions WHERE session_type = 'SUNDAY_SERVICE' AND ministry_id IS NOT NULL")).scalar():
        raise RuntimeError("Existing ministry-specific Sunday sessions need reviewed consolidation before migration.")
    op.alter_column('attendance_sessions', 'scope_type', nullable=False)
    op.alter_column('attendance_sessions', 'roster_type', nullable=False)
    op.create_check_constraint('ck_attendance_scope_ministry', 'attendance_sessions',
        "(scope_type = 'GLOBAL' AND ministry_id IS NULL) OR (scope_type = 'MINISTRY' AND ministry_id IS NOT NULL)")
    op.create_check_constraint('ck_attendance_sunday_global', 'attendance_sessions',
        "session_type != 'SUNDAY_SERVICE' OR (scope_type = 'GLOBAL' AND roster_type = 'WHOLE_CHURCH')")
    op.create_check_constraint('ck_attendance_time_order', 'attendance_sessions',
        "end_time IS NULL OR start_time IS NULL OR end_time >= start_time")
    op.create_check_constraint('ck_attendance_roster_scope', 'attendance_sessions',
        "(scope_type = 'GLOBAL' AND roster_type IN ('WHOLE_CHURCH', 'SELECTED_MEMBERS')) OR (scope_type = 'MINISTRY' AND roster_type IN ('ALL_MINISTRY_MEMBERS', 'SELECTED_MEMBERS', 'EXECUTIVES'))")
    # Freeze eligible rosters and retain every existing record, including inactive members.
    op.execute("""INSERT INTO attendance_roster_members (session_id, member_id)
        SELECT s.id, m.id FROM attendance_sessions s CROSS JOIN members m
        WHERE m.status = 'ACTIVE' AND (s.ministry_id IS NULL OR EXISTS (
            SELECT 1 FROM member_ministries mm WHERE mm.member_id = m.id
            AND mm.ministry_id = s.ministry_id AND mm.is_active = true))
        UNION SELECT session_id, member_id FROM attendance_records""")
    # A migrated baseline is identifiable; no earlier correction history is invented.
    for record in bind.execute(sa.text("SELECT id, session_id, member_id, status, marked_by_user_id, marked_at FROM attendance_records")).mappings():
        bind.execute(sa.text("""INSERT INTO attendance_audit_logs
            (id, attendance_record_id, session_id, member_id, new_status,
             changed_by_user_id, changed_at, action_type, reason)
            VALUES (:audit_id, :id, :session_id, :member_id, :status,
                    :marked_by_user_id, :marked_at, 'MIGRATED_BASELINE',
                    'Existing record retained; prior correction history unavailable.')"""),
            dict(record, audit_id=uuid.uuid4()))
    _seed_permissions(bind)



def downgrade() -> None:
    raise RuntimeError("This production migration is forward-only: restore the verified pre-upgrade backup rather than delete attendance history or security grants.")


PERMISSION_DEFINITIONS = {'ATTENDANCE_VIEW_OWN_MINISTRY': 'View assigned ministry attendance', 'ATTENDANCE_CREATE_OWN_MINISTRY': 'Create assigned ministry attendance', 'ATTENDANCE_RECORD_OWN_MINISTRY': 'Record assigned ministry attendance', 'ATTENDANCE_CORRECT_OWN_MINISTRY': 'Correct assigned ministry attendance', 'ATTENDANCE_VIEW_ALL': 'View all attendance', 'ATTENDANCE_CREATE_GLOBAL': 'Create global and ministry attendance', 'ATTENDANCE_RECORD_ALL': 'Record all attendance', 'ATTENDANCE_CORRECT_ALL': 'Correct all attendance', 'ATTENDANCE_CORRECT_CLOSED': 'Correct closed attendance sessions', 'ATTENDANCE_CLOSE_SESSION': 'Close assigned attendance sessions', 'ATTENDANCE_REOPEN_SESSION': 'Reopen assigned closed sessions', 'ATTENDANCE_LOCK_SESSION': 'Lock assigned closed sessions', 'ATTENDANCE_UNLOCK_SESSION': 'Centrally reopen locked sessions', 'ATTENDANCE_VIEW_AUDIT': 'View permitted attendance history', 'ATTENDANCE_EXPORT': 'Export permitted attendance reports', 'ATTENDANCE_SCOPE_MANAGE': 'Manage and audit ministry attendance grants'}
LEADER_PERMISSIONS = ['ATTENDANCE_CLOSE_SESSION', 'ATTENDANCE_CORRECT_OWN_MINISTRY', 'ATTENDANCE_CREATE_OWN_MINISTRY', 'ATTENDANCE_EXPORT', 'ATTENDANCE_RECORD_OWN_MINISTRY', 'ATTENDANCE_VIEW_AUDIT', 'ATTENDANCE_VIEW_OWN_MINISTRY']
OBSERVER_PERMISSIONS = ['ATTENDANCE_EXPORT', 'ATTENDANCE_VIEW_ALL', 'ATTENDANCE_VIEW_AUDIT']


def _seed_permissions(bind):
    for code, name in PERMISSION_DEFINITIONS.items():
        bind.execute(sa.text("""INSERT INTO permissions (id, code, name, module, is_active)
            VALUES (:id, :code, :name, 'Attendance', true) ON CONFLICT (code) DO NOTHING"""),
            dict(id=uuid.uuid4(), code=code, name=name))
    for code, name in [('MINISTRY_ATTENDANCE_LEADER', 'Ministry Attendance Leader'),
                       ('GENERAL_OVERSEER', 'General Overseer')]:
        bind.execute(sa.text("""INSERT INTO roles (id, code, name, is_system, is_active)
            VALUES (:id, :code, :name, true, true) ON CONFLICT (code) DO NOTHING"""),
            dict(id=uuid.uuid4(), code=code, name=name))
    grants = {'ADMINISTRATOR': list(PERMISSION_DEFINITIONS),
              'MINISTRY_ATTENDANCE_LEADER': LEADER_PERMISSIONS,
              'GENERAL_OVERSEER': OBSERVER_PERMISSIONS}
    for role_code, permissions in grants.items():
        for permission in permissions:
            bind.execute(sa.text("""INSERT INTO role_permissions (role_id, permission_id)
                SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
                WHERE r.code = :role AND p.code = :permission
                ON CONFLICT DO NOTHING"""), dict(role=role_code, permission=permission))
        for user_id in bind.execute(sa.text("""SELECT ur.user_id FROM user_roles ur
            JOIN roles r ON r.id = ur.role_id WHERE r.code = :role"""), dict(role=role_code)).scalars():
            bind.execute(sa.text("""INSERT INTO authorization_audit_logs
                (id, target_user_id, action_type, new_values)
                VALUES (:id, :user_id, 'MIGRATION_PERMISSION_GRANTS', :payload)"""),
                dict(id=uuid.uuid4(), user_id=user_id,
                     payload=json.dumps({'role': role_code, 'permissions': permissions})))
