"""add totp authentication to users

Revision ID: 53389a813b7d
Revises: 28989072b840
Create Date: 2026-10-04 23:53:51.182090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53389a813b7d'
down_revision: Union[str, Sequence[str], None] = '28989072b840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('totp_secret', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('totp_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_confirmed_at')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'totp_enabled')
    # ### end Alembic commands ###
