"""Attach sermon media and collections to existing content records.
Revision ID: bc73e2a94d16
Revises: ab61d4f83c02
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='bc73e2a94d16'
down_revision='ab61d4f83c02'
branch_labels=None
depends_on=None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sermon_playback_receipts',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index('ix_sermon_receipt_expiry', 'sermon_playback_receipts', ['expires_at'], unique=False)
    op.create_table('sermon_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cover_image_id', sa.UUID(), nullable=True),
    sa.Column('published_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','ARCHIVED')", name='ck_sermon_category_status'),
    sa.ForeignKeyConstraint(['cover_image_id'], ['website_media.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sermon_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cover_image_id', sa.UUID(), nullable=True),
    sa.Column('published_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','ARCHIVED')", name='ck_sermon_series_status'),
    sa.ForeignKeyConstraint(['cover_image_id'], ['website_media.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sermon_media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sermon_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('storage_provider', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=160), nullable=False),
    sa.Column('original_filename', sa.String(length=200), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('quality_label', sa.String(length=30), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('download_allowed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rights_attested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('error_summary', sa.String(length=300), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("media_type IN ('VIDEO','AUDIO','THUMBNAIL','CAPTION','TRANSCRIPT','DOCUMENT')", name='ck_sermon_media_type'),
    sa.CheckConstraint("processing_status IN ('UPLOADED','QUEUED','PROCESSING','READY','FAILED','DELETE_PENDING','DELETED')", name='ck_sermon_processing_status'),
    sa.CheckConstraint('file_size>=0', name='ck_sermon_asset_size'),
    sa.ForeignKeyConstraint(['sermon_id'], ['website_content.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_sermon_asset_owner_status', 'sermon_media_assets', ['sermon_id', 'processing_status'], unique=False)
    op.create_table('sermon_metrics',
    sa.Column('sermon_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('count', sa.BigInteger(), server_default='0', nullable=False),
    sa.CheckConstraint("event IN ('VIDEO_PLAY','AUDIO_PLAY','AUDIO_DOWNLOAD','VIDEO_DOWNLOAD')", name='ck_sermon_metric_event'),
    sa.ForeignKeyConstraint(['sermon_id'], ['website_content.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sermon_id', 'event')
    )
    # ### end Alembic commands ###
    op.drop_constraint('ck_website_status','website_content',type_='check')
    op.create_check_constraint('ck_website_status','website_content',"status IN ('DRAFT','PUBLISHED','ARCHIVED') OR (kind='SERMON' AND status IN ('PROCESSING','READY','SCHEDULED','FAILED'))")
    op.execute("CREATE INDEX ix_sermon_published_date ON website_content ((published_data->'data'->>'sermon_date')) WHERE kind='SERMON' AND status='PUBLISHED'")
    seed_sermon_permissions(op.get_bind())

def downgrade():
    raise RuntimeError('Sermon media history must be preserved. Restore a reviewed backup instead of deleting records.')

def seed_sermon_permissions(bind):
    from uuid import uuid4
    permissions={'SERMON_VIEW':'View sermon management','SERMON_CREATE':'Create sermon drafts','SERMON_EDIT':'Edit sermon metadata','SERMON_UPLOAD_MEDIA':'Upload authorized sermon media','SERMON_DELETE_MEDIA':'Remove sermon media','SERMON_PUBLISH':'Publish or schedule sermons','SERMON_ARCHIVE':'Archive sermons','SERMON_MANAGE_SERIES':'Manage sermon series','SERMON_MANAGE_CATEGORIES':'Manage sermon categories','SERMON_VIEW_ANALYTICS':'View sermon analytics'}
    old={'SERMON_VIEW':'WEBSITE_PAGE_VIEW','SERMON_CREATE':'WEBSITE_PAGE_CREATE','SERMON_EDIT':'WEBSITE_PAGE_EDIT','SERMON_UPLOAD_MEDIA':'WEBSITE_MEDIA_MANAGE','SERMON_DELETE_MEDIA':'WEBSITE_MEDIA_MANAGE','SERMON_PUBLISH':'WEBSITE_PAGE_PUBLISH','SERMON_ARCHIVE':'WEBSITE_PAGE_PUBLISH','SERMON_MANAGE_SERIES':'WEBSITE_PAGE_EDIT','SERMON_MANAGE_CATEGORIES':'WEBSITE_PAGE_EDIT','SERMON_VIEW_ANALYTICS':'WEBSITE_PAGE_VIEW'}
    for code,name in permissions.items():
        bind.execute(sa.text("INSERT INTO permissions(id,code,name,module,is_active) VALUES (:id,:code,:name,'Sermons',true) ON CONFLICT(code) DO NOTHING"),{'id':uuid4(),'code':code,'name':name})
        bind.execute(sa.text("INSERT INTO role_permissions(role_id,permission_id) SELECT rp.role_id,p.id FROM role_permissions rp JOIN permissions source ON source.id=rp.permission_id CROSS JOIN permissions p WHERE source.code=:old AND p.code=:code ON CONFLICT DO NOTHING"),{'old':old[code],'code':code})
    for code,name,grants in [('SERMON_EDITOR','Sermon Editor',{'SERMON_VIEW','SERMON_CREATE','SERMON_EDIT','SERMON_UPLOAD_MEDIA','SERMON_MANAGE_SERIES','SERMON_MANAGE_CATEGORIES'}),('SERMON_PUBLISHER','Sermon Publisher',set(permissions))]:
        bind.execute(sa.text("INSERT INTO roles(id,code,name,description,is_system,is_active) VALUES (:id,:code,:name,'Explicit sermon media permissions',true,true) ON CONFLICT(code) DO NOTHING"),{'id':uuid4(),'code':code,'name':name})
        for grant in grants:bind.execute(sa.text("INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code=:role AND p.code=:grant ON CONFLICT DO NOTHING"),{'role':code,'grant':grant})
