"""Add Sunday School classes enrollment lessons and separate attendance

Revision ID: c84e26f7a930
Revises: b62d08e4c715
Create Date: 2026-10-06 03:50:10.284979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid
import json

# revision identifiers, used by Alembic.
revision: str = 'c84e26f7a930'
down_revision: Union[str, Sequence[str], None] = 'b62d08e4c715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DEFINITIONS = {'SUNDAY_SCHOOL_ATTENDANCE_CLOSE': 'Close class attendance',
 'SUNDAY_SCHOOL_ATTENDANCE_CORRECT': 'Correct class attendance with a reason',
 'SUNDAY_SCHOOL_ATTENDANCE_CREATE': 'Plan and open class attendance',
 'SUNDAY_SCHOOL_ATTENDANCE_RECORD': 'Record class attendance',
 'SUNDAY_SCHOOL_ATTENDANCE_REOPEN': 'Reopen closed class attendance',
 'SUNDAY_SCHOOL_ATTENDANCE_VIEW': 'View class attendance',
 'SUNDAY_SCHOOL_CLASS_ARCHIVE': 'Deactivate and reactivate classes',
 'SUNDAY_SCHOOL_CLASS_CREATE': 'Configure Sunday School classes',
 'SUNDAY_SCHOOL_CLASS_DELETE_UNUSED': 'Delete classes without history or dependencies',
 'SUNDAY_SCHOOL_CLASS_EDIT': 'Edit class configuration',
 'SUNDAY_SCHOOL_CLASS_VIEW': 'View permitted classes',
 'SUNDAY_SCHOOL_GUARDIAN_MANAGE': 'Configure guardian relationships and contact consent',
 'SUNDAY_SCHOOL_GUARDIAN_VIEW': 'View operational guardian contacts for permitted students',
 'SUNDAY_SCHOOL_LESSON_CREATE': 'Create lesson plans',
 'SUNDAY_SCHOOL_LESSON_EDIT': 'Edit and publish permitted lessons',
 'SUNDAY_SCHOOL_LESSON_VIEW': 'View permitted lesson plans',
 'SUNDAY_SCHOOL_REPORT_EXPORT': 'Export permitted Sunday School reports',
 'SUNDAY_SCHOOL_REPORT_VIEW': 'View permitted Sunday School reports',
 'SUNDAY_SCHOOL_STUDENT_EDIT': 'Edit Sunday School admission status and notes',
 'SUNDAY_SCHOOL_STUDENT_END': 'End student enrollments',
 'SUNDAY_SCHOOL_STUDENT_ENROLL': 'Register and enroll existing members',
 'SUNDAY_SCHOOL_STUDENT_MOVE': 'Move students between permitted classes',
 'SUNDAY_SCHOOL_STUDENT_VIEW': 'View students in permitted classes',
 'SUNDAY_SCHOOL_TEACHER_ASSIGN': 'Assign teachers to permitted classes',
 'SUNDAY_SCHOOL_TEACHER_END': 'End teaching assignments',
 'SUNDAY_SCHOOL_TEACHER_VIEW': 'View teaching assignments',
 'SUNDAY_SCHOOL_VIEW': 'View Sunday School workspace',
 'SUNDAY_SCHOOL_VIEW_ALL': 'Access all Sunday School classes'}
TEACHER_GRANTS = ['SUNDAY_SCHOOL_ATTENDANCE_CLOSE', 'SUNDAY_SCHOOL_ATTENDANCE_CORRECT', 'SUNDAY_SCHOOL_ATTENDANCE_CREATE', 'SUNDAY_SCHOOL_ATTENDANCE_RECORD', 'SUNDAY_SCHOOL_ATTENDANCE_VIEW', 'SUNDAY_SCHOOL_CLASS_VIEW', 'SUNDAY_SCHOOL_GUARDIAN_VIEW', 'SUNDAY_SCHOOL_LESSON_VIEW', 'SUNDAY_SCHOOL_REPORT_VIEW', 'SUNDAY_SCHOOL_STUDENT_VIEW', 'SUNDAY_SCHOOL_TEACHER_VIEW', 'SUNDAY_SCHOOL_VIEW']

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sunday_school_students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_school_student_status'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index(op.f('ix_sunday_school_students_status'), 'sunday_school_students', ['status'], unique=False)
    op.create_table('sunday_school_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sunday_school_audit_logs_action'), 'sunday_school_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_sunday_school_audit_logs_class_id'), 'sunday_school_audit_logs', ['class_id'], unique=False)
    op.create_index(op.f('ix_sunday_school_audit_logs_member_id'), 'sunday_school_audit_logs', ['member_id'], unique=False)
    op.create_index(op.f('ix_sunday_school_audit_logs_occurred_at'), 'sunday_school_audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_sunday_school_audit_logs_session_id'), 'sunday_school_audit_logs', ['session_id'], unique=False)
    op.create_table('sunday_school_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('minimum_age', sa.Integer(), nullable=True),
    sa.Column('maximum_age', sa.Integer(), nullable=True),
    sa.Column('room_location', sa.String(length=150), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('teacher_capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_school_class_status'),
    sa.CheckConstraint('capacity IS NULL OR capacity > 0', name='ck_school_class_capacity'),
    sa.CheckConstraint('maximum_age IS NULL OR maximum_age BETWEEN 0 AND 125', name='ck_school_class_max_age'),
    sa.CheckConstraint('minimum_age IS NULL OR maximum_age IS NULL OR maximum_age >= minimum_age', name='ck_school_class_age_range'),
    sa.CheckConstraint('minimum_age IS NULL OR minimum_age BETWEEN 0 AND 125', name='ck_school_class_min_age'),
    sa.CheckConstraint('sort_order >= 0', name='ck_school_class_sort'),
    sa.CheckConstraint('teacher_capacity IS NULL OR teacher_capacity > 0', name='ck_school_class_teacher_capacity'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sunday_school_classes_status'), 'sunday_school_classes', ['status'], unique=False)
    op.create_index('uq_school_class_code', 'sunday_school_classes', [sa.literal_column('upper(code)')], unique=True)
    op.create_index('uq_school_class_name', 'sunday_school_classes', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('sunday_school_guardians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_member_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_receive_sms', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relationship IN ('PARENT','GUARDIAN','FATHER','MOTHER','RELATIVE','OTHER')", name='ck_school_guardian_relationship'),
    sa.ForeignKeyConstraint(['guardian_member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['sunday_school_students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'guardian_member_id', name='uq_school_guardian_member')
    )
    op.create_index(op.f('ix_sunday_school_guardians_guardian_member_id'), 'sunday_school_guardians', ['guardian_member_id'], unique=False)
    op.create_index(op.f('ix_sunday_school_guardians_student_id'), 'sunday_school_guardians', ['student_id'], unique=False)
    op.create_index('uq_school_primary_guardian', 'sunday_school_guardians', ['student_id'], unique=True, postgresql_where=sa.text('is_primary IS true AND is_active IS true'))
    op.create_table('sunday_school_lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('scripture_reference', sa.String(length=200), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('lesson_summary', sa.Text(), nullable=True),
    sa.Column('teacher_notes', sa.Text(), nullable=True),
    sa.Column('applies_to_all', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='DRAFT', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','ARCHIVED')", name='ck_school_lesson_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sunday_school_lessons_lesson_date'), 'sunday_school_lessons', ['lesson_date'], unique=False)
    op.create_index(op.f('ix_sunday_school_lessons_status'), 'sunday_school_lessons', ['status'], unique=False)
    op.create_table('sunday_school_attendance_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='DRAFT', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(state='DRAFT' AND opened_at IS NULL AND closed_at IS NULL) OR (state='OPEN' AND opened_at IS NOT NULL AND closed_at IS NULL) OR (state='CLOSED' AND opened_at IS NOT NULL AND closed_at IS NOT NULL)", name='ck_school_session_lifecycle'),
    sa.CheckConstraint("state IN ('DRAFT','OPEN','CLOSED')", name='ck_school_session_state'),
    sa.ForeignKeyConstraint(['class_id'], ['sunday_school_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['sunday_school_lessons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'session_date', name='uq_school_class_attendance_date')
    )
    op.create_index(op.f('ix_sunday_school_attendance_sessions_class_id'), 'sunday_school_attendance_sessions', ['class_id'], unique=False)
    op.create_index(op.f('ix_sunday_school_attendance_sessions_session_date'), 'sunday_school_attendance_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_sunday_school_attendance_sessions_state'), 'sunday_school_attendance_sessions', ['state'], unique=False)
    op.create_table('sunday_school_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('class_name', sa.String(length=150), nullable=False),
    sa.Column('class_code', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(is_current AND end_date IS NULL AND status='ACTIVE') OR (NOT is_current AND end_date IS NOT NULL AND status='ENDED')", name='ck_school_enrollment_current'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_school_enrollment_dates'),
    sa.ForeignKeyConstraint(['class_id'], ['sunday_school_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sunday_school_enrollments_class_id'), 'sunday_school_enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_sunday_school_enrollments_is_current'), 'sunday_school_enrollments', ['is_current'], unique=False)
    op.create_index(op.f('ix_sunday_school_enrollments_member_id'), 'sunday_school_enrollments', ['member_id'], unique=False)
    op.create_index('uq_school_enrollment_current', 'sunday_school_enrollments', ['member_id'], unique=True, postgresql_where=sa.text('is_current IS true'))
    op.create_table('sunday_school_lesson_classes',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['sunday_school_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lesson_id'], ['sunday_school_lessons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('lesson_id', 'class_id')
    )
    op.create_index(op.f('ix_sunday_school_lesson_classes_class_id'), 'sunday_school_lesson_classes', ['class_id'], unique=False)
    op.create_table('sunday_school_teacher_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('TEACHER','ASSISTANT_TEACHER','CLASS_COORDINATOR')", name='ck_school_teacher_role'),
    sa.CheckConstraint('(is_current AND end_date IS NULL) OR (NOT is_current AND end_date IS NOT NULL)', name='ck_school_teacher_current'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_school_teacher_dates'),
    sa.ForeignKeyConstraint(['class_id'], ['sunday_school_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sunday_school_teacher_assignments_class_id'), 'sunday_school_teacher_assignments', ['class_id'], unique=False)
    op.create_index(op.f('ix_sunday_school_teacher_assignments_is_current'), 'sunday_school_teacher_assignments', ['is_current'], unique=False)
    op.create_index(op.f('ix_sunday_school_teacher_assignments_member_id'), 'sunday_school_teacher_assignments', ['member_id'], unique=False)
    op.create_index('uq_school_teacher_current', 'sunday_school_teacher_assignments', ['class_id', 'member_id'], unique=True, postgresql_where=sa.text('is_current IS true'))
    op.create_table('sunday_school_user_class_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['sunday_school_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'class_id', name='uq_school_user_class_scope')
    )
    op.create_index(op.f('ix_sunday_school_user_class_scopes_class_id'), 'sunday_school_user_class_scopes', ['class_id'], unique=False)
    op.create_index(op.f('ix_sunday_school_user_class_scopes_user_id'), 'sunday_school_user_class_scopes', ['user_id'], unique=False)
    op.create_table('sunday_school_attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('marked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PRESENT','LATE','EXCUSED','ABSENT')", name='ck_school_attendance_status'),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sunday_school_attendance_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'member_id', name='uq_school_session_member_record')
    )
    op.create_index(op.f('ix_sunday_school_attendance_records_member_id'), 'sunday_school_attendance_records', ['member_id'], unique=False)
    op.create_index(op.f('ix_sunday_school_attendance_records_session_id'), 'sunday_school_attendance_records', ['session_id'], unique=False)
    op.create_table('sunday_school_roster_members',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['sunday_school_enrollments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sunday_school_attendance_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id', 'member_id')
    )
    op.create_index(op.f('ix_sunday_school_roster_members_member_id'), 'sunday_school_roster_members', ['member_id'], unique=False)
    op.create_foreign_key('fk_school_enrollment_student','sunday_school_enrollments','sunday_school_students',['member_id'],['member_id'],ondelete='RESTRICT')
    op.create_foreign_key('fk_school_record_roster','sunday_school_attendance_records','sunday_school_roster_members',['session_id','member_id'],['session_id','member_id'],ondelete='RESTRICT')
    bind=op.get_bind()
    for code,name in DEFINITIONS.items():
        bind.execute(sa.text("INSERT INTO permissions(id,code,name,module,is_active) VALUES (:id,:code,:name,'Sunday School',true) ON CONFLICT(code) DO NOTHING"),dict(id=uuid.uuid4(),code=code,name=name))
        if code!='SUNDAY_SCHOOL_VIEW':
            bind.execute(sa.text("INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='ADMINISTRATOR' AND p.code=:code ON CONFLICT DO NOTHING"),dict(code=code))
    for code,name,grants in (
        ('SUNDAY_SCHOOL_TEACHER','Sunday School Teacher',TEACHER_GRANTS),
        ('SUNDAY_SCHOOL_COORDINATOR','Sunday School Coordinator',list(DEFINITIONS)+['MEMBERS_VIEW_ALL'])):
        rid=bind.scalar(sa.text("INSERT INTO roles(id,code,name,description,is_system,is_active) VALUES (:id,:code,:name,:description,true,true) ON CONFLICT DO NOTHING RETURNING id"),dict(id=uuid.uuid4(),code=code,name=name,description='Sunday School capabilities; class-scoped roles require explicit account class scopes.'))
        if rid:
            for permission in grants:
                bind.execute(sa.text("INSERT INTO role_permissions(role_id,permission_id) SELECT :role,id FROM permissions WHERE code=:code ON CONFLICT DO NOTHING"),dict(role=rid,code=permission))
    for uid in bind.execute(sa.text("SELECT ur.user_id FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE r.code='ADMINISTRATOR'")).scalars():
        bind.execute(sa.text("INSERT INTO security_audit_logs(id,target_user_id,action,new_values) VALUES (:id,:uid,'MIGRATION_SUNDAY_SCHOOL_GRANTS',:values)"),dict(id=uuid.uuid4(),uid=uid,values=json.dumps({'permissions':sorted(set(DEFINITIONS)-{'SUNDAY_SCHOOL_VIEW'})})))



def downgrade() -> None:
    raise RuntimeError("Forward-only Sunday School migration; restore a verified pre-upgrade backup if required.")
