"""Persist web sessions and shared authentication rate limits

Revision ID: d95f13b8e204
Revises: c84e26f7a930
Create Date: 2026-10-06 10:53:13.265132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95f13b8e204'
down_revision: Union[str, Sequence[str], None] = 'c84e26f7a930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_rate_limits',
    sa.Column('bucket_hash', sa.String(length=64), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("bucket_hash ~ '^[0-9a-f]{64}$'", name='ck_web_rate_hash'),
    sa.CheckConstraint('expires_at > window_started_at', name='ck_web_rate_dates'),
    sa.CheckConstraint('request_count > 0', name='ck_web_rate_count'),
    sa.PrimaryKeyConstraint('bucket_hash')
    )
    op.create_index(op.f('ix_web_rate_limits_expires_at'), 'web_rate_limits', ['expires_at'], unique=False)
    op.create_table('web_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('auth_revision', sa.Integer(), nullable=True),
    sa.Column('login_method', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=32), nullable=True),
    sa.CheckConstraint("(user_id IS NULL AND auth_revision IS NULL AND login_method='anonymous') OR (user_id IS NOT NULL AND auth_revision IS NOT NULL AND auth_revision >= 0 AND login_method IN ('password','totp'))", name='ck_web_session_identity'),
    sa.CheckConstraint("session_hash ~ '^[0-9a-f]{64}$'", name='ck_web_session_hash'),
    sa.CheckConstraint('expires_at > created_at AND last_activity_at >= created_at', name='ck_web_session_dates'),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name='ck_web_session_revoked_date'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_hash')
    )
    op.create_index(op.f('ix_web_sessions_expires_at'), 'web_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_web_sessions_revoked_at'), 'web_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_web_sessions_user_id'), 'web_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_sessions_user_id'), table_name='web_sessions')
    op.drop_index(op.f('ix_web_sessions_revoked_at'), table_name='web_sessions')
    op.drop_index(op.f('ix_web_sessions_expires_at'), table_name='web_sessions')
    op.drop_table('web_sessions')
    op.drop_index(op.f('ix_web_rate_limits_expires_at'), table_name='web_rate_limits')
    op.drop_table('web_rate_limits')
    # ### end Alembic commands ###
