"use client";
import {useRef,useState,type ReactNode} from "react";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useAuth} from "@/features/auth/auth-provider";
import {useResource} from "@/features/workspace/use-resource";
import {useFilters} from "@/features/workspace/directories";
import {RecordState,Pagination,Empty} from "@/features/workspace/records-ui";
import {OperationalModal,FormActions} from "@/features/operations/operational-ui";
import {Button,Card,Badge,Input} from "@/components/ui/primitives";
import {AccessDenied} from "@/components/ui/feedback";
import {api,ApiError} from "@/lib/api/client";
import {parseContents,parseContent,parseOverview,parseMediaList,type ContentKind,type ContentRecord,type EditorialData} from "@/lib/api/content";
import {parseOptions,obj} from "@/lib/api/workspace";
import {homeSectionOrder} from '@/features/public/home-format';
const sections=[["Overview",""],["Pages","pages"],["Homepage","homepage"],["Ministries","ministries"],["Leadership","leadership"],["Sermons","sermons"],["Gallery","gallery"],["Testimonies","testimonies"],["Media","media"],["Service Times","service-times"],["Contact & settings","settings"]];
const kinds:Record<string,ContentKind>={pages:"PAGE",homepage:"HOMEPAGE",ministries:"MINISTRY",leadership:"LEADERSHIP",sermons:"SERMON",gallery:"GALLERY",testimonies:"TESTIMONY"};
const fail=(error:unknown)=>error instanceof ApiError||error instanceof Error?error.message:"Unable to save. Please try again.";
function parseChoices(value:unknown){const o=obj(value);return{ministries:parseOptions(o.ministries)};}
export function WebsiteArea({children}:{children:ReactNode}){
  const{user}=useAuth();const path=usePathname();if(!user)return null;
  if(!user.permissions.includes("WEBSITE_PAGE_VIEW")&&!user.permissions.includes("SERMON_VIEW"))return <AccessDenied/>;
  return<><nav className="school-navigation" aria-label="Website management">{sections.filter(([,id])=>(user.permissions.includes("WEBSITE_PAGE_VIEW")||id==="sermons")&&(id!=="settings"&&id!=="service-times"||user.permissions.includes("WEBSITE_SETTINGS_MANAGE"))).map(([label,id])=><Link key={id} href={"/portal/website"+(id?"/"+id:"")} aria-current={path==="/portal/website"+(id?"/"+id:"")?"page":undefined}>{label}</Link>)}</nav>{children}</>;
}
export function WebsiteOverview(){
  const{user}=useAuth();const canView=user?.permissions.includes("WEBSITE_PAGE_VIEW");
  const data=useResource(canView?"/api/v1/website/overview":null,parseOverview);
  if(!canView)return <Link className="workspace-card" href="/portal/website/sermons"><h1>Sermon Management</h1><p>Manage sermon media using your assigned permissions.</p></Link>;
  return<><div className="page-heading"><div><p className="eyebrow">PUBLISHING</p><h1>Website management</h1><p>Prepare content, review images and publish approved updates.</p></div><a href="/" target="_blank" rel="noopener noreferrer" className="button button-secondary">View public website</a></div>
    <RecordState {...data}/>{data.data&&<div className="metric-grid">{data.data.counts.map(row=><Card key={row.kind+row.status}><p className="muted">{row.kind} · {row.status}</p><strong className="metric-value">{row.total}</strong></Card>)}</div>}
    <div className="workspace-cards">{sections.slice(1).map(([label,id])=><Link className="workspace-card" key={id} href={"/portal/website/"+id}><h2>{label}</h2><p>Manage approved public {label.toLowerCase()}.</p></Link>)}</div></>;
}
export function WebsiteContentList({section}:{section:string}){
  const kind=kinds[section];const{user}=useAuth();const{params,page,update}=useFilters();const[editing,setEditing]=useState<ContentRecord|"new"|null>(null),[acting,setActing]=useState<{row:ContentRecord;action:string}|null>(null),[preview,setPreview]=useState<ContentRecord|null>(null);
  const query=new URLSearchParams({kind,page_number:String(page),search:params.get("search")??"",status:params.get("status")??"ALL"});
  const data=useResource("/api/v1/website/content?"+query,parseContents);
  return<><div className="page-heading"><div><p className="eyebrow">WEBSITE CMS</p><h1>{section==="homepage"?"Homepage":section[0].toUpperCase()+section.slice(1)}</h1><p>Draft changes stay private until an authorized publisher releases them.</p></div>{user?.permissions.includes("WEBSITE_PAGE_CREATE")&&<Button onClick={()=>setEditing("new")}>Create {kind==="HOMEPAGE"?"homepage draft":"content"}</Button>}</div>
    <form className="record-filters" onSubmit={event=>{event.preventDefault();update({search:String(new FormData(event.currentTarget).get("search")??"")});}}><label className="search-field">Search<Input name="search" defaultValue={params.get("search")??""} key={params.get("search")}/></label><Button variant="secondary" type="submit">Search</Button><label>Status<select aria-label="Content status" value={params.get("status")??"ALL"} onChange={event=>update({status:event.target.value})}>{["ALL","DRAFT","PUBLISHED","ARCHIVED"].map(value=><option key={value}>{value}</option>)}</select></label></form>
    <RecordState {...data}/>{data.data&&<>{data.data.items.length?<div className="cms-content-list">{data.data.items.map(row=><Card key={row.id} className="cms-content-row"><div><Badge tone={row.status==="PUBLISHED"?"green":"neutral"}>{row.status}</Badge><h2>{row.title}</h2><p className="muted">{row.slug} · Updated {new Date(row.updated_at).toLocaleDateString("en-GB")}</p>{row.has_unpublished_changes&&row.status==="PUBLISHED"&&<Badge>Unpublished edits</Badge>}</div>
      <div className="live-actions"><Button variant="secondary" onClick={()=>setPreview(row)}>Preview</Button>{user?.permissions.includes("WEBSITE_PAGE_EDIT")&&<Button variant="secondary" onClick={()=>setEditing(row)}>Edit</Button>}
      {user?.permissions.includes("WEBSITE_PAGE_PUBLISH")&&<><Button onClick={()=>setActing({row,action:"publish"})}>Publish</Button>{row.status==="PUBLISHED"&&<Button variant="secondary" onClick={()=>setActing({row,action:"unpublish"})}>Unpublish</Button>}<Button variant="ghost" onClick={()=>setActing({row,action:"archive"})}>Archive</Button></>}</div></Card>)}</div>:<Empty title="No website content yet">Create a draft using approved church information.</Empty>}<Pagination {...data.data} change={value=>update({page:String(value)})}/></>}
    {editing&&<ContentEditor kind={kind} record={editing==="new"?null:editing} close={()=>setEditing(null)} saved={()=>{setEditing(null);data.retry();}}/>}
    {acting&&<PublicationConfirm title={acting.action+" content"} path={"/api/v1/website/content/"+acting.row.id+"/"+acting.action} version={acting.row.updated_at} decoder={parseContent} close={()=>setActing(null)} saved={()=>{setActing(null);data.retry();}}/>}
    {preview&&<OperationalModal title={"Draft preview: "+preview.title} description="Private preview. Draft content is not indexed or publicly served." close={()=>setPreview(null)}><p className="public-summary">{preview.draft.summary}</p><div className="public-prose">{preview.draft.body}</div><Button variant="secondary" onClick={()=>setPreview(null)}>Close preview</Button></OperationalModal>}
  </>;
}
export function PublicationConfirm<T>({title,path,version,decoder,close,saved}:{title:string;path:string;version:string;decoder:(value:unknown)=>T;close:()=>void;saved:()=>void}){
  const[pending,setPending]=useState(false),[error,setError]=useState("");const busy=useRef(false);
  return<OperationalModal title={title[0].toUpperCase()+title.slice(1)} description="Confirm this change to the published website. Review content and privacy before proceeding." close={()=>{if(!pending)close();}}><form className="operational-form" onSubmit={async event=>{event.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setError("");try{await api.mutate(path,{expected_updated_at:version},decoder);saved();}catch(error){setError(fail(error));}finally{busy.current=false;setPending(false);}}}><FormActions pending={pending} error={error} close={close} label="Confirm"/></form></OperationalModal>;
}
function ContentEditor({kind,record,close,saved}:{kind:ContentKind;record:ContentRecord|null;close:()=>void;saved:()=>void}){
  const{user}=useAuth();const choices=useResource("/api/v1/website/options",parseChoices),media=useResource("/api/v1/website/media?page_size=100",parseMediaList);
  const d=record?.draft.data;const[image,setImage]=useState(d?.image_id??""),[ministry,setMinistry]=useState(record?.ministry_id??""),[images,setImages]=useState(d?.images??[]);
  const[sectionsEnabled,setSectionsEnabled]=useState<string[]>(d?.section_order??homeSectionOrder);
  const[pending,setPending]=useState(false),[error,setError]=useState("");const busy=useRef(false);
  const field=(name:string,label:string,value="",area=false,required=false)=><label key={name}>{label}{area?<textarea name={name} defaultValue={value} rows={4} maxLength={50000}/>:<Input name={name} defaultValue={value} required={required}/>}</label>;
  return<OperationalModal title={record?"Edit draft":"Create website content"} description="Use approved public wording. Published URLs stay stable; drafts need a separate publication." close={()=>{if(!pending)close();}}>
    <form className="operational-form" onSubmit={async event=>{event.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setError("");
      try{const f=new FormData(event.currentTarget);const text=(key:string)=>String(f.get(key)??"");
        const data:Partial<EditorialData>={image_id:image||null,public_name:text("public_name"),public_title:text("public_title"),meeting_information:text("meeting_information"),public_contact:text("public_contact"),speaker:text("speaker"),sermon_date:text("sermon_date")||null,scripture_reference:text("scripture_reference"),series:text("series"),youtube_url:text("youtube_url"),audio_url:text("audio_url"),images,display_order:Number(text("display_order")||"0"),hero_headline:text("hero_headline"),hero_text:text("hero_text"),primary_label:text("primary_label")||"Plan your visit",primary_href:text("primary_href")||"/new-here",secondary_label:text("secondary_label")||"Explore ministries",secondary_href:text("secondary_href")||"/ministries",section_order:sectionsEnabled,events_count:Number(text("events_count")||d?.events_count||6),ministries_count:Number(text("ministries_count")||d?.ministries_count||3),announcements_count:Number(text("announcements_count")||d?.announcements_count||3),gallery_count:Number(text("gallery_count")||d?.gallery_count||5),featured_slugs:text("featured_slugs").split(",").map(value=>value.trim()).filter(Boolean),consent_reference:text("consent_reference")};
        const body={kind,slug:kind==="HOMEPAGE"?"home":text("slug"),title:text("title"),summary:text("summary"),body:text("body"),seo_title:text("seo_title"),seo_description:text("seo_description"),data,ministry_id:kind==="MINISTRY"?ministry||null:null,member_id:record?.member_id??null,expected_updated_at:record?.updated_at??null};
        await api.mutate("/api/v1/website/content"+(record?"/"+record.id:""),body,parseContent,record?"PATCH":"POST");saved();
      }catch(error){setError(fail(error));}finally{busy.current=false;setPending(false);}}}>
      {field("title","Title",record?.draft.title??"",false,true)}{kind!=="HOMEPAGE"&&field("slug","Public URL name",record?.slug??"",false,true)}
      {field("summary","Short description",record?.draft.summary??"",true)}{field("body","Page content",record?.draft.body??"",true)}
      <label>Public image<select aria-label="Public image" value={image} onChange={event=>setImage(event.target.value)}><option value="">No image</option>{media.data?.items.map(item=><option key={item.id} value={item.id}>{item.alt_text||"Untitled image"} · {item.status}</option>)}</select></label>
      {kind==="MINISTRY"&&<><label>Linked ministry<select required aria-label="Linked ministry" value={ministry} onChange={event=>setMinistry(event.target.value)}><option value="">Select ministry</option>{choices.data?.ministries.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{field("public_name","Public ministry name",d?.public_name)}{field("meeting_information","Meeting information",d?.meeting_information,true)}{field("public_contact","Approved public contact",d?.public_contact)}</>}
      {kind==="LEADERSHIP"&&<>{field("public_name","Public name",d?.public_name)}{field("public_title","Public church title",d?.public_title)}{field("consent_reference","Approved profile consent reference",d?.consent_reference)}</>}
      {kind==="SERMON"&&<>{field("speaker","Speaker",d?.speaker,false,true)}<label>Sermon date<Input name="sermon_date" type="date" required defaultValue={d?.sermon_date??""}/></label>{field("scripture_reference","Scripture reference",d?.scripture_reference)}{field("series","Series",d?.series)}{field("youtube_url","YouTube or Vimeo link",d?.youtube_url)}{field("audio_url","Approved HTTPS audio link",d?.audio_url)}</>}
      {kind==="HOMEPAGE"&&<>{field("hero_headline","Hero headline",d?.hero_headline)}{field("hero_text","Hero supporting text",d?.hero_text,true)}{field("primary_label","Primary button label",d?.primary_label??"Plan your visit")}{field("primary_href","Primary button link",d?.primary_href??"/new-here")}{field("secondary_label","Secondary button label",d?.secondary_label??"Explore ministries")}{field("secondary_href","Secondary button link",d?.secondary_href??"/ministries")}{field("featured_slugs","Featured published URL names (comma separated)",d?.featured_slugs.join(", ")??"")}<div className="form-grid"><label>Events on Home<Input name="events_count" type="number" min={1} max={8} defaultValue={d?.events_count??6}/></label><label>Ministries on Home<Input name="ministries_count" type="number" min={1} max={4} defaultValue={d?.ministries_count??3}/></label><label>Announcements on Home<Input name="announcements_count" type="number" min={1} max={3} defaultValue={d?.announcements_count??3}/></label><label>Gallery photos on Home<Input name="gallery_count" type="number" min={1} max={5} defaultValue={d?.gallery_count??5}/></label></div><fieldset className="class-choices"><legend>Homepage sections and order</legend>{[...sectionsEnabled,...homeSectionOrder.filter(section=>!sectionsEnabled.includes(section))].map(section=><div className="live-actions" key={section}><label className="checkbox-label"><input type="checkbox" checked={sectionsEnabled.includes(section)} onChange={event=>setSectionsEnabled(previous=>event.target.checked?[...previous,section]:previous.filter(value=>value!==section))}/>{section}</label>{sectionsEnabled.includes(section)&&<><Button type="button" variant="ghost" aria-label={'Move '+section+' earlier'} disabled={sectionsEnabled.indexOf(section)===0} onClick={()=>setSectionsEnabled(previous=>{const next=[...previous],index=next.indexOf(section);[next[index-1],next[index]]=[next[index],next[index-1]];return next;})}>Earlier</Button><Button type="button" variant="ghost" aria-label={'Move '+section+' later'} disabled={sectionsEnabled.indexOf(section)===sectionsEnabled.length-1} onClick={()=>setSectionsEnabled(previous=>{const next=[...previous],index=next.indexOf(section);[next[index+1],next[index]]=[next[index],next[index+1]];return next;})}>Later</Button></>}</div>)}</fieldset></>}
      {kind==="GALLERY"&&<fieldset className="class-choices"><legend>Gallery photos</legend>{images.map((item,index)=><div className="cms-gallery-editor" key={index}><label>Photo<select aria-label={"Gallery photo "+(index+1)} required value={item.asset_id} onChange={event=>setImages(previous=>previous.map((row,i)=>i===index?{...row,asset_id:event.target.value}:row))}><option value="">Select photo</option>{media.data?.items.map(asset=><option key={asset.id} value={asset.id}>{asset.alt_text||"Untitled image"} · {asset.status}</option>)}</select></label><label>Alt text<Input required value={item.alt_text} onChange={event=>setImages(previous=>previous.map((row,i)=>i===index?{...row,alt_text:event.target.value}:row))}/></label><label>Caption<Input value={item.caption} onChange={event=>setImages(previous=>previous.map((row,i)=>i===index?{...row,caption:event.target.value}:row))}/></label><Button type="button" variant="ghost" onClick={()=>setImages(previous=>previous.filter((_,i)=>i!==index))}>Remove photo</Button></div>)}<Button type="button" variant="secondary" onClick={()=>setImages(previous=>[...previous,{asset_id:"",alt_text:"",caption:""}])}>Add photo</Button></fieldset>}
      {field("display_order","Display order",String(d?.display_order??0))}{field("seo_title","Search and sharing title",record?.draft.seo_title)}{field("seo_description","Search and sharing description",record?.draft.seo_description,true)}
      {user?.permissions.includes("WEBSITE_PAGE_PUBLISH")&&<p className="muted">Saving edits keeps the current published version unchanged. Publish separately after review.</p>}
      <FormActions pending={pending} error={error} close={close} label="Save draft"/>
    </form></OperationalModal>;
}
